### ISSUE TITLE
Filtering out noisy NE candidates

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#10]
Some suggestions to filter out phrases that are currently being picked out as candidates.
Should be fixed in CIC tokenizer (and also apply to any other tokenizer):
1. Need a list of words/phrases that are to be ignored by CIC tokenizer at the beginning of a candidate phrase.

We can start with this list (can be case ignored)
Hello
Hi
My
Our
Regarding
Quoting
On Behalf of
Behalf of

(I assume spaces are normalized in the CIC tokenizer)

Only the token above should be dropped. i.e. 
Hello Prof. ABC -> becomes Prof. ABC.
1. Totally drop exact matches with some phrases
   Mon, Tue, etc.
   Jan, Feb, etc.
   OK (just this word)

These candidates can just be ignored.
1. Drop any candidate that starts with 
   BEGIN PGP\* 
2. Drop candidates that end in the word "I"
   We see person entities like:
   Currently I...
   Unfortunately I...
   Personally I
   Recently I

**Comment by hangal** [comment]
code reviewed. just externalize this to a file.

**Comment by icgifford** [comment]
Grouping together future entity recognition enhancements.

**Comment by icgifford** [comment]
Grouping together future entity recognition requests
