### ISSUE TITLE
Missing Video file type in Advanced Search

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#106]
Version 2

The "Video" file type is missing from the drop down list in the file type list in Advanced Search. We would like to see the "Other" file types which are file types not mentioned in the drop down list.

**Comment by hangal** [comment]
Adding Video file type which got inadvertently missed out. Also reorganized the order of file types to make the more likely file types appear first. Suggest deferring the "other" file types to post-2.1, with more discussion on the specifications.
