### ISSUE TITLE
Authorities Function Will Not Work when " appear in Correspondent Addresses 

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#107]
Special Characters in Correspondent Addresses

**Comment by peterchanws** [comment]
Version 3.01
Authorities Function Not Working if " appear in Correspondent Addresses

**Comment by peterchanws** [comment]
Version 3.0.2 RC2
No problem with a fresh Bush archive
Added " in correspondent and got "ePADD error
Removed " from correspondent and still got "ePADD error

**Comment by peterchanws** [comment]
Version 3.0.2 RC2
No problem with Fikes

**Comment by hangal** [comment]
Ok, will need to debug. Let us look at it in our meeting.

**Comment by peterchanws** [comment]
Can't reproduce.
