### ISSUE TITLE
Folder View Count Not Correct

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#109]
Version 3.01

Total message count is given in Folder View Count. It should give the no of folders.

**Comment by peterchanws** [comment]
Version 3.0.2 RC2
Count not appear at all in Browse-top

**Comment by hangal** [comment]
This is by design. Please leave this issue open for the moment.

**Comment by chinuhub** [comment]
fixed.

**Comment by peterchanws** [comment]
Release 4.0-beta1 (July 5, 2017)

Fixed
