### ISSUE TITLE
Browse Popup Difficult to Navigate

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#110]
Version 3.01

Only in Mac
WIndows is fine

**Comment by hangal** [comment]
I have included this, but @joshschneider a request. Please don't use Doc files, only plaintext files to generate these lexicons. Doc does funny things to characters in the lexicon. See below -- the newlines are not correct, and further the term "driver's license" is messed up (and a few others too).

![image](https://cloud.githubusercontent.com/assets/1018175/25419646/8819a73c-2a71-11e7-8a11-c2a1811ec0c7.png)

**Comment by peterchanws** [comment]
Version 3.0.2-RC2
Fixed
