### ISSUE TITLE
Missing Variance File in epadd-settings

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#117]
Version 3.0.1

**Comment by hangal** [comment]
should be available in 3.0.1 release now.

**Comment by peterchanws** [comment]
How can I verify that?

**Comment by hangal** [comment]
That's a good question -- It is worth having a test for this.
Is there something in the Jeb Bush archive?
In RF archive, I could see Dick and Richard being merged.

**Comment by peterchanws** [comment]
Suggested authority record for "BILL Parker" is "Lundigan, William". Even you include the variance for Bill - William, there is only one word matching the suggested authority.

**Comment by hangal** [comment]
Which archive is this?
What are all the aliases for Bill Parker?

**Comment by peterchanws** [comment]
Bush small

**Comment by hangal** [comment]
Hmm... 
That's why we are matching. We are agnostic to word http://experimental.worldcat.org/fast/1498661/ has 2 names for him, 
Lundigan, Bill, 1914-1975
Parker, Larry, 1914-1975
We also consider variations in FAST, apart from variations in archive.
Let's discuss and decide the exact policy.

**Comment by peterchanws** [comment]
I see. I talked to Josh about the rules. We will need more elaborate discussion on that. I will close this issue and open a Prodpad idea for that.
