### ISSUE TITLE
Authorities Suggestions should match both first and last names

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#118]
Version 3.0.2
There are too many authority suggestions for Richard Fikes. We should limit the suggestions which match both last and first name (in both orders).

**Comment by peterchanws** [comment]
Please only use at least 2 words in the names for suggestion.

**Comment by hangal** [comment]
Peter, there were a couple of edge cases with authority matching generating a lot of hits: (Remember that ALL alternative names of a contact are looked up in the authority database, so any noisy name can lead to lots of hits)

- single names like Richard (which we can avoid by looking at names with 2 words at least)
- Names with funny characters embedded in them like double quotes or other punctuation. We now try to eliminate these before doing the lookup.

With this, the number of candidates becomes much less unwieldy. I'm also printing a warning about names that map to a lot of (> 20) authorities, which could be potentially noisy. 
Here is a list on our RF archive.

03 May 20:50:26 AuthorityMapper WARN  - Warning: many (207) hits for authority name=Jean Claude (associated with contact Jean-Claude Latombe)
03 May 20:50:37 AuthorityMapper WARN  - Warning: many (25) hits for authority name=John Murray (associated with contact John Murray)
03 May 20:50:39 AuthorityMapper WARN  - Warning: many (38) hits for authority name=James Allen (associated with contact James Allen)
03 May 20:50:41 AuthorityMapper WARN  - Warning: many (22) hits for authority name=John Anderson (associated with contact John Anderson)
03 May 20:50:42 AuthorityMapper WARN  - Warning: many (73) hits for authority name=Anderson, John (associated with contact John Anderson)
03 May 20:50:44 AuthorityMapper WARN  - Warning: many (34) hits for authority name=John Allen (associated with contact ALLEN JOHN A.)
03 May 20:50:47 AuthorityMapper WARN  - Warning: many (24) hits for authority name=John Thompson (associated with contact John Thompson)
03 May 20:50:48 AuthorityMapper WARN  - Warning: many (34) hits for authority name=Smith, Michael (associated with contact Michael A Smith)
03 May 20:50:49 AuthorityMapper WARN  - Warning: many (112) hits for authority name=T R (associated with contact Thomas Rothenfluh)
03 May 20:50:55 AuthorityMapper WARN  - Warning: many (42) hits for authority name=George John (associated with contact George John)

So common names like John Allen or Jean Claude, or names with just initials like T R can still cause noise. (The way we are doing the matching means looking up "T R" matches all people like T R Dawson, T R Stone, etc. I think the inclusion rule -- that the name we are checking like T R can be a subset of the name, not an exact full match -- is important to keep for genuine hits, so we can't do away with it.)

We can perhaps live with this. We could consider other policies like never showing more than 20 candidates. Or any other ideas?

**Comment by peterchanws** [comment]
I am fine with many hits for common names. This is the same for people who lookup LC name authority. Also, we should design better UI to show all matches rather than limiting the no of matches shown. 

Could you update the 3.1 files and I can do some test before we make the final release?

**Comment by peterchanws** [comment]
Fixed.
