### ISSUE TITLE
NER: some entities getting truncated

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#12]
on the page http://localhost:9099/epadd/entities?type=en_loc

e.g. in TW's archive, you can see:
"North Afric"
"Center of Evaluati"

It looks like some suffixes are getting stripped.
When you click on them, there are no hits, so its clearly not present in the original files in this form.

**Comment by vihari** [comment]
Cannot reproduce at the moment, will try to look at a bigger archive.
Which archive is this?
Grepping the content to see the instances of "North Afric" is a proper test than searching with Lucene.
Can you confirm if you see "North Africa" or "Center of Evaluation" recognized properly somewhere else?

**Comment by vihari** [comment]
@hangal Can you confirm this? If you still see this, can you add more info.?

**Comment by peterchanws** [comment]
Cannot reproduce.
