### ISSUE TITLE
Lexicon Test show 1 hit but system response to "No matching messages" when I click the link

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#121]
version 3.1.1
Lexicon Test show 1 hit but system response to "No matching messages" when click the link
Bush small
![screen shot 2017-05-04 at 10 12 13 am](https://cloud.githubusercontent.com/assets/1050899/25715969/4424c65a-30b2-11e7-8896-c166fe32d7ac.png)
![screen shot 2017-05-04 at 10 12 20 am](https://cloud.githubusercontent.com/assets/1050899/25715973/463dd0d0-30b2-11e7-9337-5bffabe74671.png)
[Journal of Economic Literature Classification.english.lex.txt](https://github.com/ePADD/epadd/files/976992/Journal.of.Economic.Literature.Classification.english.lex.txt)
This happened after I cleaned up the lexicon for spaces.

**Comment by hangal** [comment]
could you provide the exact lexicon file you are using, so I can reproduce it?
The file attached still has some spaces and hanging quotes. thnx

**Comment by hangal** [comment]
Also this line has some unusual formatting:
Business Administration and Business Economics; Marketing; Accounting; Personnel Economics:Accounting|"Business Administration"|"Business Economics"|Marketing|"Personnel Economics"
Is it intended?

**Comment by peterchanws** [comment]
This is the exact wording used in "Journal of Economic Literature Classification"


Peter Chan 

Digital Archivist

ePADD project Manager 

Stanford University Libraries 

Green Library, 557 Escondido Mall 

Stanford, CA  94305-6064 

(650) 924-2404 | pchan3@stanford.edu


________________________________

**Comment by hangal** [comment]
Peter, is this fixed now?

**Comment by peterchanws** [comment]
No.

**Comment by peterchanws** [comment]
Version 4.0 beta

Also, when I search "Cultural Economics", I expect hits will include words matching "Cultural Economics". However, hits include :  "economic" only.

**Comment by peterchanws** [comment]
Lexicon Test show 1 hit but system response to "No matching messages" when I click the link. We found out on Jul 13 that this was due to a hit in the attachment and the system excluded attachments when showing detail result. I think we should include attachments in lexicon search results in future.

**Comment by hangal** [comment]
Will not be fixed in 4.0, but later.

**Comment by peterchanws** [comment]
version 4.1 beta

Term shown under Lexicon Test is not response to click and thus cannot verify results.

**Comment by peterchanws** [comment]
Works after clearing cache.
