### ISSUE TITLE
Some messages are annotated with data-process="pp"

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#122]
In some cases (probably when the message has "Data" itself identified as an entity, epadd tries gto double annotate the message, and mess things up. Text like data-process="pp" leaks into the content of the message. Need more careful handling of these edge cases.

**Comment by peterchanws** [comment]
How can I test it?

**Comment by hangal** [comment]
I tested it and found it fixed on the messages I had observed the problem on. So closing.
Just watch out for this problem in the future.
