### ISSUE TITLE
Date Field Show "null" in Browse Image Using FireFox

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#123]
![screen shot 2017-05-19 at 8 27 23 am](https://cloud.githubusercontent.com/assets/1050899/26259122/68de4be4-3c7c-11e7-81b7-3dce1bf3a740.png)
Version 3.1
Date Field Show "null" in Browse Image Using FireFox. No images are shown for the messages we got from Hoover. No problem in Chrome.

Date Field Show "null" in Browse Image Using FireFox. Images appear for the messages in Bus small. No problem in Chrome.

**Comment by hangal** [comment]
will be fixed with #124

**Comment by chinuhub** [comment]
Fixed

**Comment by peterchanws** [comment]
Release 4.0-beta1 (July 5, 2017)

Fixed
