### ISSUE TITLE
Inconsistent Attachment Counts

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#124]
Version 3.1 Chrome Bush small

Other Attachment counts in browse-top is 345
Other Attachment counts in browse-top is 136 when mouse-over "Other Attachment" tab
Other Attachment counts in browse-top is 481 (284 unique) in  Attachment page
![screen shot 2017-05-19 at 10 22 36 am](https://cloud.githubusercontent.com/assets/1050899/26259401/ad9e4fe4-3c7d-11e7-9a84-bd27168b167f.png)
![screen shot 2017-05-19 at 10 22 40 am](https://cloud.githubusercontent.com/assets/1050899/26259405/b079faec-3c7d-11e7-9465-c06b74c4d24a.png)
![screen shot 2017-05-19 at 10 27 59 am](https://cloud.githubusercontent.com/assets/1050899/26259440/e4657b10-3c7d-11e7-8dbb-3bfa112b8f71.png)

**Comment by hangal** [comment]
Oops. It's a simple error. Easy to fix. Do we need to make a release?
(also, could you add a check for this in the test script?)

**Comment by peterchanws** [comment]
Since this problem appear in FireFox only, I suggest we wait for other fixes and and issue a release later.

**Comment by peterchanws** [comment]
Version 4 06-30
Fixed
