### ISSUE TITLE
Noisy location entities

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#13]
Logging some examples from TW's archive:

(lower priority than the orgs):

All caps:
END PGP SIGNATURE
DAYS OVERDUE
STRICTLY PROHIBITED
PAST PROJECTS
MAJOR PROJECTS
AM GMT (or PM PDT, etc)
MATLAB

Phrases:
App Engine
Teaching Assistants
Principal Investigator
Fourth Amendment
Autumn Quarter
Office Hours
Confidentiality Note
Summer Fellows
Groups Links
Distinguished Visitor
Invoice Number
Needs Major Revision

Words:
Im
Sales
Former
Reading
Arts
Si

**Comment by vihari** [comment]
The entities page in this version did not consider the entity score. The entries in the table were sorted based on the frequency alone, that led to a lot of noise especially with the terms with a very low entity score. 
I have indexed "Imp." folder of TW and none (almost) of these entities are to be seen above the cutoff. 
I will make the entities page do some filtering based on entity score.

**Comment by hangal** [comment]
ok. pls make the threshold a URL param so we can play around with the cutoffs if needed.
