### ISSUE TITLE
Hits are not highlighted in Entity Type Search in Advanced Search

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#130]
Version 3.1

When searching for an Entity Type through advanced search, hits are not currently highlighted.

**Comment by hangal** [comment]
we will not fix in 4.0.

**Comment by peterchanws** [comment]
version 4.1 beta
Windows - Firefox: work fine
Windows - Chrome -Entity type drop down box not working
Mac - Firefox & Chrome: work fine

**Comment by peterchanws** [comment]
works after clearing cache.
