### ISSUE TITLE
Search result(s) include terms Not exactly match search terms inside ""

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#132]
Version 4.0 beta

When I search "Cultural Economics", I expect hits will include words matching "Cultural Economics" ONLY. However, hits highlighted include :  "economic" without "cultural".

**Comment by tcpd** [comment]
I think we'll have to live with the limitation that "cultural" will be highlighted when we try to highlight "cultural economics". This seems to be a Lucene highlighter limitation.

A minor improvement we can make is:
if "cultural economics" is a hit only inside the attachment, then don't highlight "cultural" in the message at all.

**Comment by hangal** [comment]
I think we'll have to live with the limitation that "cultural" will be highlighted when we try to highlight "cultural economics". This is a Lucene highlighter limitation.

A minor improvement we can make is:
if "cultural economics" is a hit only inside the attachment, then don't highlight "cultural" in the message at all.

**Comment by hangal** [comment]
will not be fixed in 4.0

**Comment by peterchanws** [comment]
version 4.1 beta

Term shown under Lexicon Test is not response to click and thus cannot verify results.

**Comment by peterchanws** [comment]
Fixed after clearing browser.
