### ISSUE TITLE
Incorrect status messages during indexing

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#14]
Another thing I noticed when indexing TW's "Important" folder.
It says Reading 78,391 messages from Important and the blue bar makes steady rightward progress.

But the line below it keeps going from "couple of minutes" to "about a minute" etc.
then it comes to zero, says "Parsing Important" and then does the same thing all over again.
Is this some side effect of batching of 10,000 messages?

**Comment by vihari** [comment]
I fixed this in the most recent release, please confirm.

**Comment by hangal** [comment]
Not fully working yet, it says "Parsing Inbox.mbox (can take a while)" etc. during which the status bar is wrong. After it starts actually processing the second batch of messages, the status is correct.
It should not seem like it is going back.
@vihari pls verify with a large mbox file of at 20-30K messages.

**Comment by peterchanws** [comment]
Works fine in Feb 26, 2016 version
