### ISSUE TITLE
UC, Irvine - Photos and Messages Under Person Entities Not Transferred to Discovery & Delivery Module

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#144]
ePADD version Release 4.0-RC1 (July 20, 2017)  
[epadd-screenshots.docx](https://github.com/ePADD/epadd/files/1226617/epadd-screenshots.docx)
I had a video conference with UCI people and saw landing and banner photos and messages under person entities missing in Processing module. We exported the archive to delivery and discovery modules and COULD NOT see landing and banner photos and messages under person entities in both  delivery and discovery modules.  

I can't reproduce the issue in my machine. Do you have time this Fri morning at 9 am PDT to have a video conference with them?

**Comment by hangal** [comment]
@chinuhub , can you pls take a look at this?

**Comment by hangal** [comment]
Debugged this on an appraisal mode archive from UCI.
The archive is in a strange state.
In Archive.getEntitiesInDoc -> NER.getNames -> NER.getNames, the doc has 16 fields incl. the NER fields. However, when exporting from appraisal, the docs in Archive.export -> indexer.copyDirectoryWithDocFilter -> Indexer.copyDirectoryWithDocFilter, the docs read from doc = reader.document(i); have only 13 fields.
Is it something to do with entity re-recognition?

Also, need to clean up: in nertrainandrecognize.jsp,  ner.recognizeArchive() is being called twice.

**Comment by peterchanws** [comment]
User cannot find the mbox files which they used to create the archive. Issue closed until user can find the file.
