### ISSUE TITLE
How to AND multiple values for a facet type

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#145]
How can I search for correspondent = A and correspondent = B?
label = A and label = B?

Our infra may need to support this.
It is probably acceptable if the way to get to this is by clicking on facets.

**Comment by peterchanws** [comment]
We mentioned in Tips: 
Use OR, AND & NOT (Uppercase) to create Boolean logic within a field. You can use parentheses in complex expressions.
Selection across categories will return results that meet ALL of the selected options. 

Could we put  correspondent A AND correspondent B in Name or email field and label A AND label B in the future Label section in Advance search to get the result?

**Comment by hangal** [comment]
That works only for term field. ANDing in other fields is new functionality.
