### ISSUE TITLE
 Error while making a dataset out of docs

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#146]
Version 4.1
Error log sent by email

**Comment by chinuhub** [comment]
@peterchanws Is this different from UCI's issue? I only got the mail with log for that issue.

**Comment by peterchanws** [comment]
Yes, it is different.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by peterchanws** [comment]
Update "Unload Archive" from user guide.
