### ISSUE TITLE
Label management

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#147]
Create, edit, delete pre-defined labels;

Label can be classified as private / public: public label will be view-able in delivery mode

--> <Please elaborate on this, I think we didn't discuss this.> 

PC: 

Users can then tag messages with multiple pre-defined labels and / or enter free form annotations

Export function to include reports by labels as csv file

--> Please see below under 13-15

Add search by label (private / public) in advanced search

--> How does search differ based on private/public?

--> (One point for discussion: should folders be labels too?)

PC: 

-------------------------------

Scenarios:

What if a restriction label is assigned to a message and then it is deleted?

PC: The text of the label should be saved within messages (XHeadrer?). Even if the label is deleted from the list available for users to choose. It will remain in the messages.

How to remove a label?

PC: Users choose "Clear" in the drop down box to clear a Restriction label. Users uncheck the general label check box to clear a general label.

What if the same label is both a restriction label and a general label?

PC: ePADD will only act (produce reports, etc. to be defined) on messages with Restriction labels. General labels are similar to annotations and will be saved for information.

------------------------------------------------

0. Labels will be available in appraisal, processing and delivery modules only.

--> Why not discovery also (for public?). e.g. I can think of "Interesting" or "Microsoft" as a label, and it can be useful in discovery also for searching, etc.

PC: Users need to define their own labels before they can use them Since we don't have login for discovery module users, we cannot support that.

1. Add "Add / Edit restriction Labels"  and "Add / Edit general Labels" under settings for users to create restriction and general labels.

2. Use interface similar to create lexicon (see design) processing module, but there will be 3 fields per label : name, description, and optional URL.

--> Suggestion: how about if we allow users to add free-form label first? then this screen would only be for assigning metadata to existing labels.

--> For date restriction, could have a way to input dates using a date picker.

--> Users can then add meta-data to the label, such as description, URL, whether it is public/private or restricted/general. Private-public and restricted-general are mutually exclusive.

3. Restriction icon will be highlighted if any restriction label is associated with the message.

--> instead, how about if we show that label as a tag directly?

4. Only one restriction label can be set at a time.

--> Can we do away with this uh, restriction? Why not allow multiple restriction labels?

PC: We want to avoid users giving labels which are conflicting with each other.

5. Conflict popup says: "You are trying to apply the label 2050 to 120 messages. Of these, 13 already have the label 2025, 15 have the label 2055, 12 have the label 2012". Overwrite all or Cancel?

--> Thinking of a completely different interface for apply to all to make the flow simpler and cleaner. Suppose we have a popup that effectively does apply to all to all 120 messages.

It might offer a dropdown allowing you to do one of the following operations:

Add/remove Do-not-transfer flag, Add/remove reviewed flag, Add/remove label, Append/Overwrite annotation.

Conflicts will be reported up-front and confirm/cancel dialog will be provided.

Bulk apply flags can use the similar interface.

6. Facets for the restricted labels will be available in the facets panel. Restriction and label facets to be higher up on the page.

--> OK.

7. The restriction label will be invoked as a drop down box upon a click on the Restriction Icon. Users select only one of the options in the dropdown box. Label chosen will be hightlighted. Hovering on label category will show the details. 

--> Yes, hovering on a label anywhere will show details.

8. The general labels will appear as a dropdown box before the annotation box in each message. Users can choose one or more labels. Labels chosen will be hightlighted.

9. Add restriction and general labels as facets and make sure they are visible without the need to scroll down the page.

--> Yes, labels can be made available as facets. 

10. Advanced Search: Under Actions, add "Labels" - a dropdown box of all labels.

11. Advanced Search: Under Actions, change "Restricted" radio button to dropdown box of all restrictions.

--> An option is to allow users to type in whatever they want, along with auto-complete. 

Btw, users will be able to do an "OR" (label A or label B). they will not currently be able to do label A and label B.

12. In Export page, add "Labelled messages" as another options under Review messages. ???show labels

--> Not sure if this is of particular use. Isn't it simpler to just go to search?

13. In Export page, add "Restriction Details" column in the Restriction Review page. Uusers can choose to see only one???

14. In Export page (Processing module only), add Export Labelled Messages at the bottom. Users can choose to export messages under one or more labels in mbox format.

15. In Export page (Processing module only), add Export Restriction Messages at the bottom. Users can choose to export messages under one or more labels in mbox format.

--> Please clarify 13, 14, 15. Is this only for export to mbox? Not for regular export, right?

 16. APPLY TO ALL: When there are existing restrictions applied to one of more of the messages in the batch, use existing process to warn users that restriction actions had applied to one or more messages in the bath and ask if users want to overwrite to stop the process.

--> See above under #5.

17. Users can remove the label(s) / restriction by clicking the highlighted restriction and or labels in the dropdown box.

**Comment by hangal** [comment]
An important consideration is to externalize labels from the archive.
That way update/save will become faster because the whole archive does not need to be saved.
Also architecturally clean, as we can have different users have their own label set on the same archive in the future.

**Comment by peterchanws** [comment]
After discussion, we came to the following conclusion. (Josh, please correct me if I am wrong)

1. We would like to have 2 drop down boxes - one for general labels; the other for restrictions
2. Users can select only ONE restriction label; they can select multiple general labels
3. Archivists will discuss with donors to come up with an initial set of restriction labels. When none of the agreed restriction labels is appropriate and donors want to mark restriction for messages, donor can describe the restriction in the annotation box. Archivists will translate the annotation to appropriate restriction labels during processing.
4. There will be 3 properties associate with each general label: (i) creator of label - donor; archivist; researcher; (ii) ....................

**Comment by peterchanws** [comment]
Are we implementing:
Restriction period based on message date + a time period??

**Comment by hangal** [comment]
implemented, can be closed
