### ISSUE TITLE
Tell users how to report messages on the error page

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#152]
Include how to report errors accurately. e.g.

the name of the screens you went through and input boxes filled (or screen prints);
state the steps to reproduce the problem;
if you convert your email file to mbox, what software did you use and what is the original format?
how many email messages and how big (GB) are the archive?
if necessary, can you share the email files with us to find out the issue?

**Comment by peterchanws** [comment]
I assume this will be included when ePADD encountered errors and the above messages will be shown to users.

**Comment by hangal** [comment]
@peterchanws @joshschneider to suggest exact wording.

**Comment by peterchanws** [comment]
Please provide:
1. operating system & version
2. Java version
3. ram in your computer and assigned
4. epadd version
5. name of the screens you went through and input boxes filled (or screen prints); state the steps to reproduce the problem;
6. if you convert your email file to mbox, what software did you use and what is the original format?
7. how many email messages and how big (GB) are the archive?
8. if necessary, can you share the email files with us to find out the issue?

**Comment by peterchanws** [comment]
Could we add the following in the message as well:

Please provide:

operating system & version
Java version
ram in your computer and assigned
epadd version
name of the screens you went through and input boxes filled (or screen prints); state the steps to reproduce the problem;
if you convert your email file to mbox, what software did you use and what is the original format?
how many email messages and how big (GB) are the archive?
if necessary, can you share the email files with us to find out the issue?

**Comment by peterchanws** [comment]
Please update 
http://localhost:9099/epadd/debug
as well

**Comment by peterchanws** [comment]
Added
