### ISSUE TITLE
Accession merging and collections

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#153]
An archive can either be a collection or an accession. "Some metadata is associated only with a collection and is left blank if it is only an accession." - PC: I suggest we have 2 set of metadata.

The specific fields in a collection are:
-- Profile photo on collections page
-- Landing photo
-- Banner photo
-- Collection Title
-- Collection ID
-- Related/associated accession (?)
-- Finding Aid Link
-- Catalog Record Link
-- Contact Email Address
-- Biographical/Organizational History (currently "About")
-- Scope and Content Note
-- Rights and Conditions
-- Notes

(Peter, pls fill out)

The specific fields in an accession are:
-- Profile photo 
-- Accession ID
-- Scope and Content Note
-- Rights and Conditions
-- Notes

- Users import email in Appraisal. (Appraisal mode only deals with one accession at a time, no collections). Users can import email into existing accession.

- User can create a new collection in Processing module, along with collection metadata
- Users can import an accession into the collection.

- Users can also "Add New Accession" in Processing module to an existing collection which will bring users to import email to an accession directly.

- Accessions and collections will be listed on separate pages in processing mode.
- Users can edit an existing collection's metadata and an existing accession's metadata.

4. Both accessions created in Processing or imported from Appraisal will be listed by accession title, accession no, associated collection. 

5. An icon on the left of accession title will bring users to a accession metadata page.

6. Users can click on the accession no or title and ePADD will bring users directly to the Browse Top page of an accession.

8. When there is a new accession to a collection, users associate the new accession to the relative collection. A message will belong to only one accession.

8.1 For messages appear in both existing accession-A1 and new accession-A2, we will consider these messages belong to A1. As a result, these messages will NOT be counted as A2 messages.

8.2 For messages with different restriction labels in A1 and A2, ePADD will provide a report listing these messages with the different restriction labels. Restriction labels assigned in A1 will be kept in the collection. Users have to decide which conflicting actions should take precedent and edit them in the collection.

8.3 For general labels assigned to messages in A2 which are different from A1, ePADD will have both labels in the messages in the collection. Case-insensitive match is performed when merging labels. General labels and restriction labels have different namespaces. So it is possible that a message will have a general label X and a restriction label X.

8.4 For lexicons in A2 which have the same name, but are different in content from A1, ePADD will add A2 as suffix to the lexicon name and make both available in the collection.

8.5 For correspondents, ePADD will keep contacts in A1 and A2 which don't intersect (i.e. no email or name is commin) as is. If there is a conflict (i.e. name or email of a contact in A1 intersects with name or email in multiple contacts in A2; or vice versa), the non-common contacts will be pulled out in a new contact and marked as conflicting. All changed contacts will also be highlighted somehow. In terms of marking, there can be some options to indicate whether to indicate whether A1 is trusted, or A2 is trusted, or both.

8.6 For entities which were merged by users and had different components in A1 and A2,  ePADD will provide a report listing those entities and their associated components. ePADD will keep the association as defined in A1 and users have to edit the entities accordingly.

9. The report for 8.2 and 8.3 will list message by message id, label in A1, label in A2. The message Id will be a hyperlink to the message page of the message to the collection (which is already loaded up in ePADD. There will not be a way to load the new accession being merged.)

**Comment by peterchanws** [comment]
Here are the wire frames of the new screens.
![processing - collections- edit collection metadata](https://user-images.githubusercontent.com/1050899/32397570-af14d858-c0a7-11e7-9d10-d2d463b3af7c.png)
![appraisal - import an accession](https://user-images.githubusercontent.com/1050899/32397571-af2a7e9c-c0a7-11e7-9be6-a2c754feb929.png)
![processing - accessions](https://user-images.githubusercontent.com/1050899/32397573-af46c354-c0a7-11e7-946e-0a7c8d97a6f3.png)
![processing - collections - info](https://user-images.githubusercontent.com/1050899/32397574-af6415bc-c0a7-11e7-92b6-d48afcc1a0b9.png)
![processing - collections- edit collection metadata b](https://user-images.githubusercontent.com/1050899/32397575-af7e6f20-c0a7-11e7-8286-97217c8a47d6.png)

**Comment by hangal** [comment]
closing now.
