### ISSUE TITLE
Testing multiple people with the same name

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#154]
With the new release, we are adding support for the address book to allow the same name for multiple contacts (This was not possible earlier). 

This scenario could happen when a user edits the address book. e.g., If the same name N belongs to 2 different email addrs E1 and E2, all of N, E1, E2 will initially be merged into a single contact. Then the user may split the contact and make 2 separate ones (N, E1) and (N, E2). In that case, N is associated with both contacts.

If the same email address is present in different contacts, ePADD's behavior is undefined.
(there should be a warning to indicate this situation) 

@peterchanws, could you pls remember to test this case? e.g. in advanced search, messages related to both people should show up. 

@chinuhub

**Comment by peterchanws** [comment]
Will do.

**Comment by hangal** [comment]
@peterchanws we just need more testing of this specific case.

**Comment by hangal** [comment]
@joshschneider Could we ensure the address book help message makes this feature clear?

**Comment by peterchanws** [comment]
fixed.
