### ISSUE TITLE
Reindex (after adding messages) enhancements

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#157]
1. keep contacts in A1 (before index) and A2 (after index) which don't intersect (i.e. no email or name is common) as is. If there is a conflict (i.e. name or email of a contact in A1 intersects with name or email in multiple contacts in A2; or vice versa), the non-common contacts will be pulled out in a new contact and marked as conflicting. All changed contacts will also be highlighted somehow. In terms of marking, there can be some options to indicate whether to indicate whether A1 is trusted, or A2 is trusted, or both.

2. For entities which were merged by users and had different components in A1 (before index) and A2 (after index), ePADD will provide a report listing those entities and their associated components. ePADD will keep the association as defined in A1 and users have to edit the entities accordingly.

**Comment by hangal** [comment]
Move to version 6.

**Comment by icgifford** [comment]
Re-test with latest version
