### ISSUE TITLE
Cross Collections Search Improvements

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#158]
1. Search results hyperlink to messages from different archives

2. This implies multiple archives will be opened at the same time.

**Comment by chinuhub** [comment]
It is fixed in the latest draft release uploaded on git.

**Comment by peterchanws** [comment]
l found the following issues:

1. When I started the program, the system shows "No archive in session. Please go to Collections and load an archive.". It would be better better if the system go to the Collection home page: http://localhost:9099/epadd/collections.

2. When I click the results, the system open the related archives. However, it didn't narrow the records to the hits. 
Search result:
Stanford Center on Longevity | 55 |   | Mar 11, 2009 - Aug 20, 2014
Open all messages in the archives.
<img width="979" alt="screen shot 2017-10-30 at 2 37 43 pm" src="https://user-images.githubusercontent.com/1050899/32197086-2e541fb4-bd80-11e7-8723-d98a176bf934.png">
<img width="1162" alt="screen shot 2017-10-30 at 2 38 20 pm" src="https://user-images.githubusercontent.com/1050899/32197087-30876dfe-bd80-11e7-9ddc-49a4f6806907.png">

**Comment by hangal** [comment]
Changes to be made:
1. Correspondents and entities in body/subject which will be listed differently.
Jeb Bush in the body will have a different line than Jeb Bush as a correspondent.

2. Message count will not be shown for now because we can't show it accurately.

3. Link to messages with term will have phrase search (with quotes).

**Comment by peterchanws** [comment]
Since the message pages don;t have information about what collection user are looking, Josh and I suggest the attached message screen (see attached). We will talk to Sudheendra to finalize the screen.
![message browsing with collection id bar to aid with cross collection search](https://user-images.githubusercontent.com/1050899/32397554-8556b612-c0a7-11e7-8741-0cc7efd3b447.png)
