### ISSUE TITLE
Upload Correspondent list

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#167]
Upload Correspondent list not working.
We need to provide an option for it: either in advanced search or off the options/settings pages.

System will return to label page after users upload the csv file. (Important)

**Comment by chinuhub** [comment]
Should user return to label page or the browse page? I think once user returns to the browse page he can go to bulk-label/ bulk-annotation to change labels/annotations for these messages. This flow also allows him to look at all the messages for given correspondents.

**Comment by chinuhub** [comment]
As per discussion with @peterchanws and @hangal we open label page after uploading the csv file. This page shows the label information for all messages which contain the addresses given in the csv file ( in cc,to,bcc).

**Comment by peterchanws** [comment]
Tested on Bush (small). Fixed.
