### ISSUE TITLE
Conversion tool to v5

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#168]
Conversion tool to v5 will use this flow:

- Use a new conversion version of v4 to export labels, annotations, address book, authorities file.
- Reimport all mail folders into epadd v5 (assumption: people have access to the original files)
- then copies the above files into new v5 archive folder.

**Comment by peterchanws** [comment]
The tool will migrate: "Do Not Transfer", "Transfer with Restriction", "Review" and correspondent file.
Users need to manually transfer merged entities, authorities, and annotations.
