### ISSUE TITLE
Special characters in merge report

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#169]
Need to properly support i18n chars or special chars like ampersand (&) and single/double quotation marks in archive title, people names, etc on all pages.

Util.escapeHTML() should be used when rendering user-generated fields.
and encode has to be used when submitting forms that may have such fields.

**Comment by peterchanws** [comment]
Peter / Chinmay will test on their ends.

**Comment by peterchanws** [comment]
can't find special characters. will re-open the issue if problem re-appear.
