### ISSUE TITLE
Formatting of Correspondents sorted by Alpha Need Improvement

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#172]
Proper line feed needed

**Comment by hangal** [comment]
can you paste a screenshot?

**Comment by peterchanws** [comment]
<img width="302" alt="screen shot 2018-02-12 at 7 21 13 pm" src="https://user-images.githubusercontent.com/1050899/36132069-fac3c2e2-1029-11e8-8134-0e03c60a2dc4.png">

**Comment by peterchanws** [comment]
Fixed.
