### ISSUE TITLE
Unique ID for messages

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#176]
We currently use folder-message num as a unique ID for messages.
This is not robust w.r.t. folder names or message positions. e.g.
A folder may be reimported, but with some messages deleted. Then the message #s changed.
Or the same folder may be in different accounts.

A better approach is to compute the unique ID based on the message.
We could use Util.hash(EmailDoc.getSignature()).

However, for messages with hackyDates, we can't rely on this signature because .
It is possible that there is an entire mbox file with missing dates. In this case, signature will return the same value for all messages with the same to-from-cc-bcc headers.

**Comment by peterchanws** [comment]
Please add messages with unique ids in the Data Report

**Comment by peterchanws** [comment]
implemented in ver 5
