### ISSUE TITLE
Clean up addressbook

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#18]
The addressbook for TW is unacceptable. Look at what it takes to fix it.

Avoid merging based on 
single names ("Scott")
any name with a special char (including @ -- usually email addresses)
any name with the words: subscription, support, customer, Facebook, "by way of ....", "via an", "autoresponder", "vacation", "admin", "team", 

Avoid merging based on any email address with no-reply@, info@ (happens for evite)

Names with only punctuation chars should not even be considered names and should not be put in the address book.

**Comment by hangal** [comment]
Peter, could you please test this?

**Comment by peterchanws** [comment]
Version July 1
Implemented
