### ISSUE TITLE
jim.horne@fldoe.org grouped under "Jim Horne"  appear as separate entry in browse correspondent

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#180]
<img width="338" alt="screen shot 2018-02-23 at 8 24 06 am" src="https://user-images.githubusercontent.com/1050899/36604709-59435e6c-1873-11e8-9107-78917a0ba21e.png">
<img width="1022" alt="screen shot 2018-02-23 at 8 23 53 am" src="https://user-images.githubusercontent.com/1050899/36604724-671e4470-1873-11e8-8bf3-4c915bff734b.png">

**Comment by chinuhub** [comment]
@peterchanws Could you please send me 'Addressbook' file for this archive? It is stored in the session subdirectory of the archive.

**Comment by peterchanws** [comment]
Any updates?
