### ISSUE TITLE
Lexicon categories more than 10  are not hyperlinked 

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#19]

**Comment by vihari** [comment]
@peterchanws Could you elaborate. I tried 11 lexicon categories on TW's archive with no problem except that the eleventh lexicon in the second page of the list of lexicons is not hyperlinked. 
Please provide more details like lexicons, the archive on which you tried, what you mean by inconsistency and the log if available.

**Comment by peterchanws** [comment]
Josh reported the issue. I tried myself and I got the same result as you did. I think the issue should be categories in second page are not hyperlinked. They need to be hyperlinked - same as categories in first page. Sorry for the confusion.

**Comment by joshschneider** [comment]
Issue was lack of hyperlinking beyond first 10 categories, reported here:  https://epadd.nimeyo.com/85/unable-identified-messages-from-added-lexicon-categories.


Josh

________________________________

**Comment by hangal** [comment]
@vihari pls look into this.

**Comment by peterchanws** [comment]
Version Jan 26 (Feb 18)
Bush Small; Win 10
Fixed
