### ISSUE TITLE
ePADD - Archivematica integration

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#190]
[epadd-appraisal-bag.zip](https://github.com/ePADD/epadd/files/1864414/epadd-appraisal-bag.zip)
[epadd-appraisal-only-blobs-bag..zip](https://github.com/ePADD/epadd/files/1864415/epadd-appraisal-only-blobs-bag.zip)
[NYPL_Archivematica_Tests.zip](https://github.com/ePADD/epadd/files/1864416/NYPL_Archivematica_Tests.zip)
[nypl-experiments.zip](https://github.com/ePADD/epadd/files/1864417/nypl-experiments.zip)

Hi Peter,

I created a folder in your shared folder with the files after they have gone through Archivematica. The file starting with M123 is the epad-appraisal-bag, and M124 is the epadd-appraisal-only-blobs-bag. This page can help familiarize you with the structure of the Archivematica AIP: https://www.archivematica.org/en/docs/archivematica-1.6/user-manual/archival-storage/aip-structure/#aip-structure. 

It might be helpful for you to have the xml file of the processing configuration I used for this transfer. This file outlines all of our processing decisions like which tool we chose for file format identification, whether we wanted compressed packages extracted, etc. My authorization to access our VMs isn't working but if Nick's is, he might be kind enough to grab it and add it to the folder. Otherwise, I'll troubleshoot and get it to you later this week.

Susan

**Comment by peterchanws** [comment]
Need UI in export screen to export blobs as bag  (wire frame will come soon)
Need UI to import normalized blobs (wire frame will come soon)
Need UI to let users know if an attachment is normalized (wire frame will come soon)

**Comment by peterchanws** [comment]
Info on CVS format
https://www.loc.gov/preservation/digital/formats/fdd/fdd000323.shtml

**Comment by peterchanws** [comment]
If we provide ability for users to see 'cleaned" name and "non-normalized" file in message screen, I suggest we keep the original layout of Browse Attachment.

**Comment by peterchanws** [comment]
Add a section on collection page:
Preservation actions:
xxx files renamed
yyy files normalized

**Comment by chinuhub** [comment]
When user selects to download the original file he will get the renamed file. This is because the original file no longer exists in the blob folder. cleanup process renames the file while keeping the format unchanged.

**Comment by peterchanws** [comment]
I see. We will put this in release note.

**Comment by peterchanws** [comment]
1. The following is missing:
epadd will add the following section on collection page immediately above the "Edit Metadata" button:
Preservation actions:
xxx files renamed
yyy files normalized

2. Got HTTP Status 404 when downloading attachment university letter modified.doc

3.  Our internal attachment prefix was show with filenames. It should be removed.
![capture](https://user-images.githubusercontent.com/1050899/41984023-737e2320-79e4-11e8-81b7-20c4329a68b1.PNG)

4. Search for Glacier_Bkgrd-4230cb7d-37ac-43cb-914d-8918c488696d.tif which was migrated by Archivematica got No matching result.

**Comment by peterchanws** [comment]
ver 6 beta1 2July
Info needed not shown with the archive from NYPL
![capture](https://user-images.githubusercontent.com/1050899/42181607-411acafe-7df0-11e8-89ee-cf6e91d6e75b.PNG)

**Comment by peterchanws** [comment]
Got that using another machine.
![capture](https://user-images.githubusercontent.com/1050899/42182157-2ccc1c9a-7df2-11e8-998a-c6475761436f.PNG)

It will be better if you can give one more line break after the info.

**Comment by peterchanws** [comment]
@chinuhub 
a file which was renamed and converted from 
107.Fiesta Bkgrd.jpg
to
107.Fiesta_Bkgrd-da1a0626-bea9-403a-818f-f04bb7d0934a.tif

Icon did NOT show original filename

**Comment by peterchanws** [comment]
ver epadd-standalone-v6-beta1-3July
issue fixedf

**Comment by peterchanws** [comment]
need to talk to NLPY on the exclusion of metadata file in their processing

**Comment by chinuhub** [comment]
Removed the hidden file .metadata from blobs folder. It was not of much use because the data saved in this file was anyway being saved in default.archive.v2 serialzed file as well.

For now, we will avoid having hidden files in our archive.

**Comment by chinuhub** [comment]
Modified blob store so that now .metadata file will not be generated. Moreover, bag validation and creation will not take hidden files into consideration. We needed to change bagit library code because existing one was forcing the condition "Every file in the payload directory should be present in at least one manifest file" which is not true if a hidden file/folder gets generated in the payload directory of the bag. Because of this modification in bagit jar we will no longer use maven dependency but rather use jar for that. The modified file is attached here just for the future reference.

**Comment by peterchanws** [comment]
Need to work with NYPL to ensure v7 work with their script.

**Comment by icgifford** [comment]
Suggest testing with latest version
