### ISSUE TITLE
ePADD scaling to 750K messages

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#192]
From Prodpad:

Hardware: 
Mac Mini: 2.5 GHz Intel Core i5 (Passmark 4,121); 16 GB RAM Use 12GB for ePADD
Software: Mac OX 10.12; Chrome
Collection: Terry Winograd; 650,000 messages; 5235 / 1883? folders
Fetch & index time: 8.5 hrs
Load 1st screen from Collection (1st time): 2 min
Load 1st screen from Collection (2nd time): 5 sec
Load Correspondents (139,105): 25 sec
Load Person (132,551/471,524) : 2 min 37 sec
Load Browse Images (31,274) 18 sec
Search "MIT" 8 sec 11,558 hits

MacPro: 3.7 GHz Quad-Core Intel Xeon E5 (Passmark 9,677); 12GB RAM Use 10GB for ePADD
Software: Mac OX 10.12; Chrome
Fetch & index time: 6.5 hrs
Load 1st screen from Collection: 4 sec
Load Correspondents (139,105): 20 sec
Load Person (132,551/471,524) : 2 min 16 sec
Load Browse Images (31,274) 12 sec
Search "MIT" 6.5 sec 11,558 hits

PC: Core i7-5820K 3.3GHz (Passmark 15,419); 32GB RAM Use 28 GB for ePADD
Software: Win 10 64-bit; Chrome
Fetch & index time: 3.15  hrs
Load 1st screen from Collection:   54 sec
Load Correspondents (139,105): 16 sec
Load Person (132,551/471,524) : 1  min 2  sec
Load Browse Images (31,274)  18 sec
Search "MIT"  4.7 sec 11,558 hits

Same configuration except using SSD drive instead of 7200 rpm spining drive for data
Load 1st screen from Collection:   66 sec
Load Correspondents (139,105): 16 sec
Load Person (132,551/471,524) : 1  min 56  sec
Load Browse Images (31,274)  13 sec
Search "MIT"  3.9 sec 11,558 hits

Using Version Jan 18, 2018
PC: Core i7-5820K 3.3GHz (Passmark 15,419); 32GB RAM Use 28 GB for ePADD
Load 1st screen from Collection:    sec
Load Correspondents (139,105):  sec
Load Person (132,551/471,524) :   min   sec
Load Browse Images (15,727 / 27,693)  15 sec
Search "MIT"  4 sec 11,558 hits

MacPro: 3.7 GHz Quad-Core Intel Xeon E5 (Passmark 9,677); 12GB RAM Use 10GB for ePADD
Software: Mac OX 10.12; Chrome
Fetch & index time:  5 hrs 20 min
Load 1st screen from Collection:  sec
Load Correspondents (123,207):  20 sec
Load Person (121,179) : 3 min 8 sec
Load Browse Images (31,274)  sec
Search "MIT" 12 sec 11,257 hits

Full Jeb Bush (280,769 unique messages)
MacPro: 3.7 GHz Quad-Core Intel Xeon E5 (Passmark 9,677); 12GB RAM Use 10GB for ePADD
Software: Mac OX 10.12; Chrome
Fetch & index time:  1 hrs 49 min
Load Correspondents (109,498):  15 sec
Load Person (61,558) : 1 min 6 sec
Load Browse Images (9115 / 19,058)  7 sec
Search "god" 6 sec 10,523 hits

Josh would like to see everything done within 10 sec. I think 15 sec. is fine. Please let us know what trade off we will face if we reduce the response time to within 10/15 sec.

We should also add notes telling people the system is working during the waiting time.

**Comment by hangal** [comment]
We need to maintain an in-memory mapping of docs to entities and types to speed up some of this.
Need to estimate the memory footprint based on how many entities, and how many unique entities.

**Comment by peterchanws** [comment]
Use ver 5.1 to check response time.

**Comment by peterchanws** [comment]
ver 6 beta Jun 18
Bush full

Time taken to load archive in processing module: 11:45 min

**Comment by peterchanws** [comment]
In addition to scale to 750 messages per archive, we would like the system to scale to 1.5 million messages in cross collection search.

**Comment by peterchanws** [comment]
Terry 656,620 messages; 141,640 correspondents; 127,705 person entity
Ver 6, Mac mini, 16GB RAM, Core i5
FireFox 61.0.2
Took 38 sec. to land on browse correspondent page
Took 3 min. 8 sec. to land on person entity page
Took  to land on all messages page
Chrome 68.0
Took 34 sec. to land on browse correspondent page
Took 2 min. 55 sec. to land on person entity page
Took  > 13 min to land on all messages page

**Comment by hangal** [comment]
what was the firefox timing for all messages?

**Comment by chinuhub** [comment]
In the latest draft uploaded on github (24th Sep) we added caching for correspondent and lexicon listing. This should improve the timings. Need to be done for entities too. 
We are working on improving the loading time of message browse window now.

**Comment by peterchanws** [comment]
v7 26Sep; dmg file (4GB?); Bush (full) - 280,786 total messages; Mac 4 cpu; 16GB RAM
Indexing of Bush (full) took 12 hrs. 
Chrome
Took 11 sec to land in Correspondent page
Took 5 sec to land in General lexicon
Took 9 sec to land in Sensitive lexicon
Took 9 sec to search "stanford" with 586 hits

Firefox
Took 7 sec to land in Correspondent page
Took 1 sec to land in General lexicon
Took 1 sec to land in Sensitive lexicon
Took 35 sec to search "stanford" with 586 hits

**Comment by peterchanws** [comment]
@chinuhub @hangal 
v7 24Sep; dmg file

Terry (full) - Messages: 656,269; Attachments: 59,080 

Mac Pro 12GB RAM; MacOS 10.13; Chrome; 

Took 72 hrs to complete indexing the archive
Load 1st screen from Collection (1st time): 1:28 min
Took 27 sec to land in Correspondent page
Took 1:41 min to land in General lexicon
Took 2:45 min to land in Sensitive lexicon
Took 1:40 min to land Image browsing page
Took 1:19 min to search "mit" with 11606 hits
Took 3:37 min to close archive in processing module

**Comment by peterchanws** [comment]
Terry (full) - Messages: 656,269; Attachments: 59,080
v7 2 Oct jar 16GB RAM
Macbook Pro 16GB RAM 4 cores cpu; MacOS 10.14; Chrome v69;

Load 1st screen from Collection (1st time): ? min
Took 22 sec to land in Correspondent page
Take ? sec to land on browse result of correspondent "BEN" 26,709 messages
Took 12 sec to land in General lexicon result page
Took 10 sec to land in Sensitive lexicon result page
Took 9 sec to land Image browsing page
Took 7.5 sec to search "mit" with 11606 hits
Took ?? min to export to processing
Took 3:37 min to close archive in processing module

**Comment by peterchanws** [comment]
Terry-full + Bush-full: Messages: 656,269; Attachments: 59,080
v7 2 Oct jar 16GB RAM

MacOS 10.14; Macbook Pro 16GB RAM 4 cores cpu;

Chrome v69
Load 1st screen from Collection (1st time):  sec
Took 50 sec to land in Correspondent page
Take  sec to land on browse result of correspondent "Brian Lee" 2,146 messages
Take  sec to land on browse result of correspondent "Mobile Media" 39,738 messages
Took 0.5 sec to land in General lexicon result page
Took 1 sec to land in Sensitive lexicon result page
Took 10 sec to land Image browsing page
Took 9 sec to search "mit" with 11606 hits
Took  sec to close archive in processing module

Firefox v62
Load 1st screen from Collection (1st time):  sec
Took  sec to land in Correspondent page
Take  sec to land on browse result of correspondent "Brian Lee" 2,146 messages
Take  sec to land on browse result of correspondent "Mobile Media" 39,738 messages
Took  sec to land in General lexicon result page
Took  sec to land in Sensitive lexicon result page
Took  sec to land Image browsing page
Took  sec to search "mit" with 11606 hits
Took  sec to close archive in processing module

**Comment by peterchanws** [comment]
Terry-full + Bush-full: Messages: 742,486 incoming 288,525 outgoing ; Attachments: 59,080
v7 2 Oct jar 16GB RAM

Win 10Mac; HP 16GB RAM 4 cores cpu; error prompt up, no attachment in resulting index

Firefox v62: browser.cache.memory.max_entry_size from 5120 to 1280000
Load 1st screen from Collection (1st time): sec
Took 15 sec to land in Correspondent page
Take 7 sec to land on browse result of correspondent "Kathleen Shanahan" 23,568 messages
Take 4.5 sec to land on browse result of correspondent "Yablonski, Brian" 39,738 messages
Took 8.5 sec to land in General lexicon result page
Took 14 sec to land in Sensitive lexicon result page
Took 10 sec to land Image browsing page
Took 9 sec to search "mit" with 11606 hits
Took sec to close archive in processing module

**Comment by peterchanws** [comment]
Bush-full:
v7 8 Oct jar 16GB RAM

Win 10; MacBook Pro 16GB RAM 4 cores cpu; error prompt up

Messages: 280,768 Incoming: 201,889 Outgoing: 103,848
Attachments: 43,009 Images: 19,269 Documents: 19,824 Others: 3,916 

Load 1st screen from Collection (1st time): 2 sec
Took 6 sec to land in Correspondent page
Took 5 sec to land on browse result of correspondent "Kathleen Shanahan" 22,791 messages
Took 38 sec to land in Person Entity result page
Took 1 sec to land in Other Entities result page
Took  3.5 sec to land in General lexicon result page
Took  5 sec to land in Sensitive lexicon result page
Took 9  sec to land Image browsing page
Took 5 sec to search "computer" with 9,337 hits
Took 20 sec to land Advance Search page
Took 19 sec to close archive in processing module

**Comment by peterchanws** [comment]
Terry-full + Bush-full:
v7 12 Oct jar 16GB RAM

Win 10; MacBook Pro 16GB RAM 4 cores cpu;

Messages: 937,036; 735,275 incoming 288,239 outgoing ; Attachments: 50635 image; 51,402 others
Load 1st screen from Collection (1st time): sec
Took 11 sec to land in Correspondent page
Took 7 sec to land on browse result of correspondent "Kathleen Shanahan" 23,578 messages
Took 2:26 min to land on 6152 organization entities from other entities page
Took 2:24 min to land on 621 museum entities from other entities page
Took 0.5 sec to land in General lexicon result page
Took 0.5 sec to land in Sensitive lexicon result page
Took 57/20 sec to land Image browsing page (50948)
Took 38 sec to land Other attachment page (37041)
Took 7 sec to search "mit" with 11606 hits
Took 2 sec to land Advanced Search page
Took sec to close archive in processing module

**Comment by peterchanws** [comment]
v7 14 Oct jar 16GB RAM

Win 10; MacBook Pro 16GB RAM 4 cores cpu;

Messages: 937,036; 735,275 incoming 288,239 outgoing ; Attachments: 50635 image; 51,402 others
Load 1st screen from Collection (1st time): sec
Took ? sec to land in Correspondent page
Took ? sec to land on browse result of correspondent "Kathleen Shanahan" 23,578 messages
Took 2:43 min to land on Person entity page from browse top
Took 1 sec to land on other entities from browse top
Took 2:25 min to land on 6152 organization entities from other entities page
Took ? min to land on 621 museum entities from other entities page
Took ? sec to land in General lexicon result page
Took ? sec to land in Sensitive lexicon result page
Took 51 sec to land Image browsing page (50948)
Took ? sec to land Other attachment page (37041)
Took ? sec to search "mit" with 11606 hits
Took ? sec to search "" and got xxxxx messages
Took ? sec to land Advanced Search page
Took ? sec to close archive in processing module

**Comment by peterchanws** [comment]
v7 beta
Messages: 1,092,943; Attachments: 113,868; Images: 52,340l Documents: 47,983; Others: 13,545
Windows 10; 32GB assigned
Load 1st screen from Collection (1st time): sec
Took ? sec to land in Correspondent page
Took ? sec to land on browse result of correspondent "Kathleen Shanahan" 23,578 messages
Took 2:43 min to land on Person entity page from browse top
Took 1 sec to land on other entities from browse top
Took 2:25 min to land on 6152 organization entities from other entities page
Took ? min to land on 621 museum entities from other entities page
Took ? sec to land in General lexicon result page
Took ? sec to land in Sensitive lexicon result page
Took 51 sec to land Image browsing page (50948)
Took ? sec to land Other attachment page (37041)
Took ? sec to search "mit" with 11606 hits
Took ? sec to search "" and got xxxxx messages
Took ? sec to land Advanced Search page
Took ? sec to close archive in processing module

**Comment by peterchanws** [comment]
@chinuhub 
Improvement of loading time on the following:
Took 3:20 min to land on Person entity (191,204 entries) page from browse top
Took 29 sec to land Other attachment page (37,636)

**Comment by peterchanws** [comment]
ver 7 beta Nov 22
Messages: ; Attachments: ; Images:  Documents: ; Others: 
Windows 10; 16GB assigned
Took 2 min to Load 1st screen from Collection
Took 4 sec to land in Correspondent page
Took 11 sec to land on browse result of correspondent "Scott Klemmer" 14,264 messages
Took 1 sec to land on entities from browse top
Took 3:20 min to land on Person entity (191,204 entries) page from browse top
Took 1 sec to land on lexicon result page
Took 1 sec to land in Sensitive lexicon result page
Took 40 sec to land Image browsing page (52,340)
Took 29 sec to land Other attachment page (37,636)
Took 5.5 sec to search "mit" with 12167 hits
Took 41 sec to search "" and got 1,092,942 messages
Took 1 sec to land Advanced Search page
Took 1:31 min to close archive in processing module

**Comment by peterchanws** [comment]
ver 7 beta Nov 22
OS 10.14, 16GB RAM
Collection: Terry - Full
Messages: 660,022; Incoming: 529,360; Outgoing: 155,105
Attachments: 59,478; Images: 31,641; Documents: 21,883; Others: 5,954

Took ??? min to Load Browsetop/Dashboard from Collection
Took 3 sec to land in Correspondent page
Took 18 sec to land on browse result of correspondent "Scott Klemmer" 14,243 messages
Took 1 sec to land on entities from browse top
Took 13 sec to land on Person entity (127,034 entries) page from browse top
Took  min to load "terry winograd" (126,292) messages
Took 3:09 min to load "denver stutler" (1929) messages
Took 1 sec to land on lexicon result page
Took 1 sec to land in Sensitive lexicon result page
Took 5.36 sec to load hits for "Employment" (21,847) messages
Took 11.23 sec to land Image browsing page (9294 unique)
Took 9.36 sec to land Other attachment page (37,636)
Took 2 sec to search "god" with 10,544 hits
Took 7.7 sec to search "" and got 280,924 messages
Took 1 sec to land Advanced Search page
Took 1:06 min to close archive in processing module

**Comment by peterchanws** [comment]
ver 7 beta Nov 26
Win 10, 16GB RAM, Firefox
Collection: Bush - Full
Messages: 280,924; Incoming: 252,383; Outgoing: 28,845
Attachments: 43,072; Images: 19,313; Documents: 19,837; Others: 3,922

Took ?? min to Load Browsetop/Dashboard from Collection
Took 1.5 sec to land in Correspondent page
Took 5 sec to land on browse result of correspondent "Bradshaw Sally" 5726 messages
Took 1 sec to land on entities from browse top
Took 4 sec to land on Person entity (61,724 entries) page from browse top
Took 12 sec to load "bush jeb" (126,292) messages
Took 2.5 sec to load "denver stutler" (1929) messages
Took 1 sec to land on lexicon result page
Took 1 sec to land in Sensitive lexicon result page
Took 5.36 sec to load hits for "Employment" (21,847) messages
Took 11.23 sec to land Image browsing page (9294 unique)
Took 9.36 sec to land Other attachment page (37,636)
Took 2 sec to search "god" with 10,544 hits
Took 7.7 sec to search "" and got 280,924 messages
Took 1 sec to land Advanced Search page
Took 1:13min to close archive in processing module

**Comment by peterchanws** [comment]
ver 7 beta Nov 26
Win 10, 64GB RAM, Chrome
Collection: Terry - Full
Messages: 660,022; Incoming: 529,360; Outgoing: 155,105
Attachments: 59,269; Images: 31,618; Documents: 21,780; Others: 5,871

Took ?? min to Load Browsetop/Dashboard from Collection
Took 6 sec to land in Correspondent page (30,992 entries)
Took 6 sec to land on browse result of correspondent "Scott Klemmer" 14,243 messages
Took 1 sec to land on entities from browse top
Took 23 sec to land on Person entity (127,397 entries) page from browse top
Took 8 sec to load "terry winograd" (101,337) messages
Took 3 sec to load "diamond larry" (3,438) messages
Took 1 sec to land on lexicon result page
Took 1 sec to land in Sensitive lexicon result page
Took 7 sec to load hits for "Employment" (22,445) messages
Took 24 sec to land Image browsing page (19,469 unique)
Took 19 sec to land Other attachment page (37,636)
Took 6 sec to search "mit" with 11,603 hits
Took 26 sec to search "" and got 660,022 messages
Took 1 sec to land Advanced Search page
Took 1:13min to close archive in processing module

**Comment by hangal** [comment]
So all that seems pretty good, right?
How much time to import?

**Comment by peterchanws** [comment]
Yes. Very good. Howerver, both Mac and Windows gave me a null error 2 hrs after indexing started. I made sure I closed all other program and restarted. The error message still appeared and I just let the program to continue indexing. It took ~10 hrs  to finish indexing. I will use a machine with 32 GB RAM to run it again when I return to Stanford.


Peter


Peter Chan 

Digital Archivist

ePADD project Manager 

Stanford University Libraries 

Green Library, 557 Escondido Mall 

Stanford, CA  94305-6064 

(650) 924-2404 | pchan3@stanford.edu


________________________________

**Comment by peterchanws** [comment]
Load Terry again after restart ePADD. Took 9:15 min

**Comment by peterchanws** [comment]
Log uploaded to Google Drive

**Comment by peterchanws** [comment]
v7 Dec 1

Win 10, 64GB RAM, Chrome
Messages: 1,092,943; Incoming: 961,828; Outgoing: 155,568
Attachments: 59,333; Images: 52,340; Documents: 48,002; Others: 13,555
Took ? sec to Load Browsetop/Dashboard from Collection
Took 5.3 sec to land in Correspondent page (30,750 entries)
Took 12 sec to land on browse result of correspondent "Scott Klemmer" 14,264 messages
Took 1 sec to land on entities from browse top
Took 39 sec to land on Person entity (190,490 entries) page from browse top
Took 9.1 sec to load "terry winograd" (101,750) messages
Took 4.4 sec to load "diamond larry" (3,438) messages
Took 0.7 sec to land on lexicon result page
Took 0.7 sec to land in Sensitive lexicon result page
Took 6.1 sec to load hits for "Employment" (23,885) messages
Took 38 sec to land Image browsing page (29,504 unique)
Took 42 sec to land Other attachment page (50,389)
Took 4.4 sec to search "mit" with 12,171 hits
Took 41 sec to search "" and got 660,022 messages
Took 1 sec to land Advanced Search page
Took ?? min to close archive in processing module

**Comment by peterchanws** [comment]
v7 Jan 16

Win 10, 32GB RAM, Chrome
Messages: 1,079,086; Incoming: 1,079,086; Outgoing: 0
Attachments: 109,463; Images: 49,083; Documents: 47,080; Others: 13,300
Took 6:52 min to Load Browsetop/Dashboard from Collection
Took 1:02 min to land in Correspondent page (328,682 entries)
Took 6 sec to land on browse result of correspondent "Scott Klemmer" 14,143 messages
Took 2 sec to land on entities from browse top
Took 42 sec to land on Person entity (190,490 entries) page from browse top
Took 9.1 sec to load "terry winograd" (99,976) messages
Took ? sec to load "diamond larry" (3,438) messages
Took 0.7 sec to land on lexicon result page
Took 0.7 sec to land in Sensitive lexicon result page
Took 5.5 sec to load hits for "Employment" (23,868) messages
Took 16 sec to land Image browsing page (26,331 unique)
Took 21 sec to land Other attachment page (49,257 unique)
Took 3 sec to search "mit" with 12,171 hits
Took 50 sec to search "" and got 1,079,086 messages
Took 1 sec to land Advanced Search page
Took 4:30 min to close archive in processing module

**Comment by peterchanws** [comment]
v7 Jan 17

MacBook Pro (2 core) 16GB RAM (Terry)
Messages: 660,022; Incoming: 660,022; Outgoing: 0
Attachments: 59,412; Images: 31,624; Documents: 21,864; Others:5,924
Took  5:21 min to Load Browsetop/Dashboard from Collection
Took 46 sec to land in Correspondent page (158,719 entries)
Took 11 sec to land on browse result of correspondent "Scott Klemmer" 14,244 messages
Took 2 sec to land on entities from browse top
Took 32 sec to land on Person entity (127,395 entries) page from browse top
Took 21 sec to load "terry winograd" (101,375) messages
system unresponsive to entries in search box
Took 8 sec to load "diamond larry" (3,438) messages
Took 1 sec to land on lexicon result page
Took 0.7 sec to land in Sensitive lexicon result page
Took 1:23 sec to load hits for "Employment" (22,459) messages
Took 36 sec to land Image browsing page (26,331 unique)
Took 24 sec to land Other attachment page (23,182 unique)
Took 18 sec to search "mit" with 12,171 hits
Took 1:18 min to search "" and got 660,022 messages
Took 1 sec to land Advanced Search page
Took 4:30 min to close archive in processing module

**Comment by peterchanws** [comment]
ver Jan 22

Win 10, 32GB RAM, Chrome, epadd.exe
Messages: 1,079,086; Incoming: 1,079,086; Outgoing: 0
Attachments: 109,463; Images: 49,083; Documents: 47,080; Others: 13,300
Took 15 min to Load Browsetop/Dashboard from Collection
Took 54 sec to land in Correspondent page (328,682 entries)
Took 10 sec to land on browse result of correspondent "Scott Klemmer" 14,143 messages
Took 2 sec to land on entities from browse top
Took 42 sec to land on Person entity (190,490 entries) page from browse top
Took 23 sec to load "terry winograd" (99,976) messages
system unresponsive to entries in search box
Took 3.3 sec to load "diamond larry" (3,438) messages
Took 0.7 sec to land on lexicon result page
Took 0.7 sec to land in Sensitive lexicon result page
Took 8.5 sec to load hits for "Employment" (23,868) messages
Took 25 sec to land Image browsing page (26,331 unique)
Took 31 sec to land Other attachment page (49,257 unique)
Took 5 sec to search "mit" with 12,171 hits
Took 3 min to search "" and got 1,079,086 messages
Took 1 sec to land Advanced Search page
Took 1 sec to close archive in processing module
