### ISSUE TITLE
highlighting of correspondent name not working when name is capitalized

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#193]
This screen is part of the messages when the correspondent cvaidya@... is clicked from the correspondents page. However, it does not highlight CVAIDYA@
 
![image](https://user-images.githubusercontent.com/1018175/38172543-9c920914-35cb-11e8-8c3c-914aaf0de1c7.png)

**Comment by chinuhub** [comment]
Could not reproduce it. Source code suggests that this highlighting should work because the match happens after converting the contact names to lower case characters (in EmailRender.java::formatAddressesAsHTML method).

**Comment by peterchanws** [comment]
ver 7 beta nov 26
issue not found

**Comment by icgifford** [comment]
Comments suggest has been fixed.
