### ISSUE TITLE
Slight misformatting in message browse

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#197]
![image](https://user-images.githubusercontent.com/1018175/39049173-f8ef8ff0-44bd-11e8-9d47-4bb952e5b2b8.png)

The HTML looks like this: (Maybe a span within a span shouldn't be allowed?)
![image](https://user-images.githubusercontent.com/1018175/39049213-34bfeafc-44be-11e8-890c-c466952de673.png)

But more importantly, it looks like "<melissa" was taken as an HTML tag:

![image](https://user-images.githubusercontent.com/1018175/39049255-683b3f62-44be-11e8-9485-33db6d9640d7.png)

**Comment by hangal** [comment]
Also this:
![image](https://user-images.githubusercontent.com/1018175/39050225-3b40ba06-44c2-11e8-8688-0d6b5a28b94f.png)

**Comment by peterchanws** [comment]
What can we do?

**Comment by peterchanws** [comment]
ver jan 29-2

<img width="959" alt="screen shot 2019-01-29 at 11 55 04 am" src="https://user-images.githubusercontent.com/1050899/51936330-cbb56f80-23bc-11e9-810d-8493883b5a35.png">

**Comment by icgifford** [comment]
Suggest testing with latest version
