### ISSUE TITLE
Searching for messages with date 1960 to 1963 resulted all messages in the archive

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#201]
Version 4.1
Fikes full
Discovery module
Searching for message with date 1960 to 1963 resulted all messages in the archive
When I specified 1960-01-01 to 1963-12-31, I got 1 hit
I suggest we give people an error message asking them to input yyyy-mm-dd if they didn't do that.

**Comment by peterchanws** [comment]
I suggest we use the calendar widget we used in appraisal:
![screen shot 2018-05-11 at 9 21 59 pm](https://user-images.githubusercontent.com/1050899/39953690-e0ed79c2-5565-11e8-9544-d0cc1dd4528e.png)

**Comment by chinuhub** [comment]
It already uses that. We can disable manual editing but the UI for that (disabled input box) doesn't look sleek.

**Comment by peterchanws** [comment]
Please disable manual editing

**Comment by peterchanws** [comment]
Can we get a widget which allow users to change year and month separately.

**Comment by chinuhub** [comment]
Added support for the separate selection of years and months. Disabled manual entry of a date. The range of years allowed for now is 1930-2030.

**Comment by peterchanws** [comment]
bug fixed and feature added
