### ISSUE TITLE
Many error messages appear in importing accession in procession module

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#209]
ver 5.1 May 1; MCEWAN archive

1. Message unavailable.

![missing message capture](https://user-images.githubusercontent.com/1050899/39550880-b9fcafcc-4e17-11e8-885a-3cfba7c0d75b.JPG)

2. Many error messages (below) appear when user import accession in processing mode: (detail log in Google Drive).

02 May 16:26:48 Archive WARN - Some serious error: For document G:\IN_PROGRESS\MCEWAN_MS4902_processed\CONVERTED_EMAIL_MBOX_ORIGINAL\Sent\Mail Sent 2014 Q1.mbox Msg#33c35fbf9babb78144151b0475a37b194c1d707baa950b2fe0e0ee2bc047ec80 (Subject:Re: April 6-9) date 10 February 2014 no lucene doc found
02 May 16:26:48 Indexer WARN - REAL WARNING: lookup failed for id f6c03097d60538e0b6e1888edb1e58a0355704ff24082b8fccf4fa0c7d32b927: 0 documents found for this id

**Comment by peterchanws** [comment]
same thing happen to Fikes

**Comment by chinuhub** [comment]
If I understand correctly you do not see any message in the browse window in processing mode. Is it right?

**Comment by peterchanws** [comment]
v5.1 May 4
The error messages do not appear in this build.
