### ISSUE TITLE
Message body not redacted in Discovery mode

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#213]
v5
When I exit and return to ePADD, messages are redacted again.
See discovery folder in Google Drive
v4
User encountered the same case:

Also, I should mention, a strange thing happened in one of the ePADD session while we were playing with the Discovery module. I did not quite see what happened, but when one of the workshop participants refreshed her browser an email which had been suppressed suddenly became visible! We first thought that the ePADD file for Delivery might have gone into the Discovery folder – but this was not the case when we looked. (Note that this problem only affected one participant/ePADD session out of 20). Have you come across this before in version 4?

**Comment by chinuhub** [comment]
Could you please elaborate on the use case again? This is my understanding;

You indexed an archive.. exported to processing.. imported in processing.. exported to discovery.. copied to epadd-discovery folder and you saw that messages were not redacted. Is it right?

On the issue of some message becoming visible again I don't remember encountering it in v4. @hangal Did you notice anything like that?

**Comment by peterchanws** [comment]
You indexed an archive.. exported to processing.. imported in processing.. exported to discovery.. copied to epadd-discovery folder and you saw that messages were not redacted. Correct

**Comment by chinuhub** [comment]
I tried with Fikes 2003. I could not see it on my machine on this mbox. Which archive did you try this case on?
Can you please try on Fikes 2003 so that at least we are sure that we see the same behaviour on this small archive?

**Comment by peterchanws** [comment]
I can't reproduce the problem after I quit and restart, You may need to look at the log I uploaded in Google drive.

**Comment by chinuhub** [comment]
@peterchanws I don't see the discovery folder shared on google drive. Could you please send me the link for that?

**Comment by chinuhub** [comment]
The discover folder shared on google drive shows the redacted messages when opened in ePADD. It implies that ePADD correctly exported the redacted messages in the discovery archive. After exporting to discovery from processing it seems that you used change mode feature. @hangal  This is not well tested, I thought it was only for debugging purpose. It seems that when mode is changed we should force the removal of saved archive object from the global map.

**Comment by hangal** [comment]
yes, that is correct. another possibility would be to stop and relaunch the whole application.

**Comment by peterchanws** [comment]
I am fine telling users that "it was only for debugging purpose" and the proper way to start discovery mode is to use the discovery mode standalone program.

**Comment by hangal** [comment]
I think we can explicitly take discovery mode out of the dropdown, since it
is special - needs to be secure, etc.
the other 3 modes can remain.
