### ISSUE TITLE
Search for Irregular messages

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#214]
Users need an easy way to retrieve irregular messages. 

1st approach

Summary of error types:

The summary are hyper linked to messages with respective errors.

12 messages with a guessed date
6 messages with a probably bad date
2,502 attachments with no filename
4 duplicate messages
131 other errors

![capture](https://user-images.githubusercontent.com/1050899/39654346-41761802-4fa9-11e8-82c2-5b9f126df45b.PNG)

2nd approach

Add following labels to these irregular messages during indexing

guessed date
no date
message with bad date
attachments with no filename
other errors

Users can found these messages in the label functions

**Comment by peterchanws** [comment]
System to assign labels to these messages

**Comment by peterchanws** [comment]
In the ePADD weekly meeting on Jul 26, we agreed that the label approach is better.

**Comment by chinuhub** [comment]
Out of the following 5 labels,
guessed date
no date
message with bad date
attachments with no filename
other errors

1. Instead of two labels "guessed date" and "no date" we should have only one label. Say "No date".

**Comment by peterchanws** [comment]
Agree.

**Comment by chinuhub** [comment]
Added support in the latest draft of 23rd Sep. For searching such messages user can use label search facilities.

**Comment by peterchanws** [comment]
v7 26Sep; Bush (full), MacOS 0.13; Chrome

In data report:
564 messages without To, Cc or Bcc addresses
283 messages without a from address
54 messages with a probably bad date
68 attachments with no filename
8,272 duplicate messages
6,291 duplicate attachments
2,984 other errors

In label summary page:

Do not transfer | Restriction | 0 | Not editable | Not removable
Attachments without file name | General | 68 | Not editable | Not removable
Possibly Bad Date | General | 52 | Not editable | Not removable
No Date | General | 1 | Not editable | Not removable
Reviewed | General | 0 | Edit | Remove
Cleared For Release | General | 0 | Not editable | Not removable
Other errors while parsing | General | 0 | Not editable | Not removable

I suggest we synchronize what the parser consider as error to the system labels

**Comment by peterchanws** [comment]
Messages with dates Aug 12, 2013 is considered as message with bad date. Why?
<img width="1040" alt="screen shot 2018-09-27 at 2 07 39 pm" src="https://user-images.githubusercontent.com/1050899/46174763-c9040b80-c25e-11e8-9f3f-a289bed368a0.png">

**Comment by chinuhub** [comment]
The difference (52 vs 54) appears because two messages, although parsed, are not added to the archive. The reason being that they have unusual long size of message body. It happens because the attachment also gets interpreted as part of the body. We have this check to prevent cases where the whole attachment is also considered as part of the body (wrongly during parsing) and as a result the field in lucene will have unnecessarily huge size.

I suggest that we should not consider the information earlier present in the data report as a golden one. Because not all message, about which we store information in the data report, get added in archive.
@hangal Any comments on this?

**Comment by hangal** [comment]
@chinuhub that's a good point. I think we're doing the right thing here, we need to document it to explain to users.

**Comment by hangal** [comment]
as decided today, we will not remove any messages. we can just truncate and label it.

**Comment by peterchanws** [comment]
Please move the summary of errors in the report to the top.

**Comment by peterchanws** [comment]
Please ensure 
# of incoming; outgoing, total messages
# of image, non-image attachments

are also on top section

**Comment by peterchanws** [comment]
v7 10 Oct, Win 10, Terry+Jeb,

<img width="299" alt="annotation" src="https://user-images.githubusercontent.com/1050899/46780329-b6e39c00-cd39-11e8-976d-29b385f72f39.png">

**Comment by chinuhub** [comment]
Spec for classifying errors as labels:

**Errors classified as Formatting and Parsing Errors" label."**
1. dataErrors.add("part is null: " + folder_name() + " idx " + messageNum);

2. dataErrors.add("Dirty message part, has conflicting message part headers."  + folder_name() + " Message# " + messageNum);

3.dataErrors.add("Unsupported encoding: " + folder_name() + " Message #" + messageNum + " type " + type + ", using brute force conversion");

4.dataErrors.add("Unhandled part content, " + folder_name() + " Message #" + messageNum + "Java type: " + o.getClass() + " Content-Type: " + p.getContentType());

5.dataErrors.add("Skipping message as it seems to have very long words: " + ed);
======================================

**Errors classified as "Errors in attachment" label."**
1.dataErrors.add("Ignoring attachment for " + folder_name() + " Message #" + messageNum + ": " + Util.stackTrace(e));

2.dataErrors.add("Unable to read attachment name: " + folder_name() + " Message# " + idx);

3.dataErrors.add("attachment filename is null for " + sanitizedFName + " Message#" + idx + " assigning it the name: " + tempFname);
