### ISSUE TITLE
35193 hits of docId = XXX is not unique. Found: 2 hits!

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#215]
See log in Google drive

35193 hits)
	Line 1: 04 May 13:54:22 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 9528f724b81dd8809b9564dc709c8906d79e1461b061e94719028e4a183f2785 is not unique. Found: 2 hits!

**Comment by chinuhub** [comment]
@peterchanws Do you remember the case I showed you on Fikes 2003? There were three messages with null to,cc,bcc,from and same date. Above message "found duplicate ..." comes because of such messages because all of them are assigned the same uniqueID.
I have fixed this but as a result of this change the number of documents imported will not match with v4. Now there will be more duplicates. Although that is the right behaviour and we can explain that to clients. If this change is accepted then I can prepare a build with this fix and upload it today.

**Comment by peterchanws** [comment]
But we have 35193 hits of docId !!

**Comment by peterchanws** [comment]
See below for samples. I believe they are not  messages with null to,cc,bcc,from and same date. 

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = a74c025cc2db0685e1f123a1be6f4acc5f2e60100fb561e134bda6fb30bf3bf2 is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 309ae98a49c3d00bc42c917322d3fec0ad7f37ea59435ddf2ca0710b3191d97f is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = c388cc696a7b65b9246dfaa6b913fa0bcd1f99f355a2ad735bf52cbf5b1b9f1e is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 5507b03c49553fd4f1adade6bfe18bb4ca20aaac8ce5a99f4a3fa536f6c24403 is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 1b1a5872c05a27177a63af94100a6eb31f11a182661920c64a05f35aaebec5ba is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 5d09f3ccd58a1fc5a3b26be00198de23fa6bf0cb1c6fba0ff30fe872957afe1d is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 06539363e1c8acbccd75264f2b886a929ddf545ed82bb03419acce6d6ec37e05 is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 507a3c2f8acb86cf9675d996b686531b245124170cc61a5d5890aaf107e7e5c7 is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = a7660a3277fb2e7dcafabcec1b184a1c0dfac9d6b849b6cbfc2861ca083f4b04 is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 28656077a352bc67f0c1a738236564b0c22d040ce9155099a435ed8be1361662 is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = bac5124129ce382ad1a24a7fedeb0b2bea79f9d1dbdd93424ceb7dad4878f4c8 is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 2c3866ed6488f2fd9444141a03534c66e0948147073adf3b4a744255c2ead54a is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 9a06af6b169f8527fe05b063fa17445e3e8d9541ece3d49e18bf7637e2b960e1 is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 4b8c6499a540d21053b562eeda08af4644ed9a332f0cc389531810d31c31e39a is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 3553c1468c35b764959349403cd76886ec242fb5558fdb7727206790278a4a09 is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 7960d54867ed26e0634c5ae145ba3d04bf877638f5f4ac62e4dd2d818711f976 is not unique. Found: 2 hits!

07 May 07:45:14 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 78d9bcc552b85a7701cfe3b79ed5e41d1101405cf3822c4a3b920d2e7a5d4fa0 is not unique. Found: 2 hits!

**Comment by peterchanws** [comment]
I have just perform a switch mode from appraisal to processing for the Mceman archive and there are ~3000  "docId = XXX is not unique. Found: 2 hits!". How can we confirm if they are messages with null to,cc,bcc,from and same date as you mentioned.

**Comment by peterchanws** [comment]
Got similar problem with Fikes 2000 and 2003.

**Comment by peterchanws** [comment]
ver epadd-standalone.v5.1-8May.jar  Fikes 2000 and 2003.
Got the following errors

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = e951326b7a3d744c92751525964d148ab55e1f7017f6fd81e504d7f1bc633d04 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 98a79e4e553bdaa9b601d8f0d442bf6b06e304858799241ac926f2f4d8390537 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 98a79e4e553bdaa9b601d8f0d442bf6b06e304858799241ac926f2f4d8390537 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 8c7185a80b85a5fb81552150f7526e3b2994f8616111f4c6c46b962bfdc4db1b is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 8c7185a80b85a5fb81552150f7526e3b2994f8616111f4c6c46b962bfdc4db1b is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 94086ce1ac484675a27e554bd5ba0253031108f3b3c64d955f821f8ff72f12e7 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 94086ce1ac484675a27e554bd5ba0253031108f3b3c64d955f821f8ff72f12e7 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 403a456dc73584a6014cfd6e73a1f3748dcbfb6d3c54a84522471426131c6e08 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 403a456dc73584a6014cfd6e73a1f3748dcbfb6d3c54a84522471426131c6e08 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 09ded53a3e6171bea8c4ef372782b0c1ea59f81f0d22c48950503e0a0422e90a is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 09ded53a3e6171bea8c4ef372782b0c1ea59f81f0d22c48950503e0a0422e90a is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = f23e757531376871cae10945f1148b711aee2f87bbf3411a9f0a33b54f344b61 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = fa3ee01d2d20a25965f0feb2fc69cae0b5e4b7eee2562d791b0111e5cf074790 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = f23e757531376871cae10945f1148b711aee2f87bbf3411a9f0a33b54f344b61 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = fa3ee01d2d20a25965f0feb2fc69cae0b5e4b7eee2562d791b0111e5cf074790 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = c44f1410e8cf7684aeec02b6909a266504d97cbcae6403fae088b32eee9aee3b is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = c44f1410e8cf7684aeec02b6909a266504d97cbcae6403fae088b32eee9aee3b is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 6e14ba0a36014fa29bcbdff6645b94300ceee79d3acee27b282fa7ac31cd3853 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = ec20e0bc2142548aaa8ddd79fefc40c9abc72e738606a5c3b9bbf80323eb25de is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 6e14ba0a36014fa29bcbdff6645b94300ceee79d3acee27b282fa7ac31cd3853 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = ec20e0bc2142548aaa8ddd79fefc40c9abc72e738606a5c3b9bbf80323eb25de is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 29a9410e25f097c647c23ef73d422396845e445d741255fbc0357c1081f36636 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 29a9410e25f097c647c23ef73d422396845e445d741255fbc0357c1081f36636 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 0a56e7b0d51cd5c2cf42a6843b059100b3499b4141e8b63a8c0744045c2158aa is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 0a56e7b0d51cd5c2cf42a6843b059100b3499b4141e8b63a8c0744045c2158aa is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = c64f385402dd3c9cfe63abceea03221f6e507e265d9c4280b87dde16d74a3267 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = c64f385402dd3c9cfe63abceea03221f6e507e265d9c4280b87dde16d74a3267 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = dcb687d9acc40a7d5d0fa9be08f29aa11d8337e9fbea18ae49cd5d627c90a503 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = dcb687d9acc40a7d5d0fa9be08f29aa11d8337e9fbea18ae49cd5d627c90a503 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 0049c0867f582480a691086af25e1e181425034ba8c9b77b707830e79bca54af is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 0049c0867f582480a691086af25e1e181425034ba8c9b77b707830e79bca54af is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = eb9853b81bde381c23bd33139de391fe051b988a578a750656ac23ccd06790cc is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = eb9853b81bde381c23bd33139de391fe051b988a578a750656ac23ccd06790cc is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = eb5aee062e8418b7f26b473c016dea601e5d98efe20972228d3131fa27a6c834 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = eb5aee062e8418b7f26b473c016dea601e5d98efe20972228d3131fa27a6c834 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 3474c1716e830d4b11ec1f84146225eb945706cc6d934482c6aeda2ce9a0f8d6 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 3474c1716e830d4b11ec1f84146225eb945706cc6d934482c6aeda2ce9a0f8d6 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 32fd97e25cc07f5a256a6910c3a26228fba042cb2e0d222e01acda30a2c4eb1a is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 3beba79e0eacab8acddffaec19b797ad8f7054d8bdb4d3d69f0e10a5486377e2 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 3beba79e0eacab8acddffaec19b797ad8f7054d8bdb4d3d69f0e10a5486377e2 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = ee16c79937cf4d6baa7792250d5f475e085d9d659f3d9094a8ac94e3e24802fa is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = ee16c79937cf4d6baa7792250d5f475e085d9d659f3d9094a8ac94e3e24802fa is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 66427e9ba384386ea4730ae0b0f67dad904ba8afe2107270224c52fef83fff66 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 66427e9ba384386ea4730ae0b0f67dad904ba8afe2107270224c52fef83fff66 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = c0c4105b18a7db16282bcbf0d17074006254af37976f478035a9fe36f6174a33 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = c0c4105b18a7db16282bcbf0d17074006254af37976f478035a9fe36f6174a33 is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 32fd97e25cc07f5a256a6910c3a26228fba042cb2e0d222e01acda30a2c4eb1a is not unique. Found: 2 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 196c521ce23092026e574acde12b766abff7884b05cb84e1fb975ab749525657 is not unique. Found: 3 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 196c521ce23092026e574acde12b766abff7884b05cb84e1fb975ab749525657 is not unique. Found: 3 hits!

08 May 07:54:50 Indexer WARN  - REAL WARNING: Soft assert failed! docId = 196c521ce23092026e574acde12b766abff7884b05cb84e1fb975ab749525657 is not unique. Found: 3 hits!

**Comment by chinuhub** [comment]
Am I correct in assuming that the above messages are from Fikes 2003? If yes, could you please pass me the appraisal folder for fikes 2003. I can't see this issue with 8 May version.

**Comment by peterchanws** [comment]
It come from year 2000 and 2003. Uploading appraisal to Google drive now.

**Comment by peterchanws** [comment]
I assume the flow you suggested doesn't require re-index:
imported archive-> from appraisal exported to processing-> changed mode to processing from setting-> imported the accession with accession id 1- In the log window I did not see the soft warn message.
Do you want me to re-index the appraisal archive.

**Comment by chinuhub** [comment]
Sorry for the confusion. By 'imported archive' I meant import and index mbox. 2003 Fikes is small. Could you please index it afresh and then send me the appraisal folder if you see the same messages again?

**Comment by peterchanws** [comment]
No errors in Fikes 2003. 
However, there are still ~3000 "Indexer WARN  - REAL WARNING: Soft assert failed! docId = xxx is not unique. Found: 2 hits" errors when I import the Mcewan accession to processing. I used the May version to index full Mcewan archive already. See messages in Google drive.

**Comment by peterchanws** [comment]
I used the May 9 version trying to narrow down the files which cause the error without success. I tried the following period separately:
1997-2000
2001-2002
2003-2006
2007-2009
2010-2010
2011-2012
2013-2014
No "Indexer WARN  - REAL WARNING: Soft assert failed! docId = xxx is not unique. Found: 2 hits!" message appear when I import the respective accession archives to processing module.

**Comment by peterchanws** [comment]
Ver 5.1 May 10
Mcewan - received all
The errors disappear.
