### ISSUE TITLE
Error! Code 2, Message: Unable to import accession: java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#216]
ver 5.1 May 9 build 2
Fikes Full (accession 1 & 2)
Happen when import accession in processing
See log in Google Drive

**Comment by chinuhub** [comment]
@peterchanws  Could you please check this issue with 10 May version?

**Comment by peterchanws** [comment]
ver 5.1 May 10
Fikes Full (accession 1 & 2)
Error not appear
