### ISSUE TITLE
Original text & subject of all non-restricted messages as individual TXT files

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#222]
This is part of #196 

Processing module ONLY
Add a new section: 
Specification for "Original text & subject of all non-restricted messages as individual TXT files":

use message-XXXXXX as filename (XXXXXX is numeric start from 1)
file contain subject, original text, message id
no need to compress the files
Since this operation may take a long time, please show "Downloading" and "Download completed" during the process.

![40452554-192cc790-5e97-11e8-95f6-dbb2dba376f8](https://user-images.githubusercontent.com/1050899/41250125-df62ac68-6d6a-11e8-884f-c3f67b763bf7.png)

**Comment by chinuhub** [comment]
@peterchanws It will be easier for us to zip all those text files together in a zip file and then download it. This is how even gmail handles downloading more than one files (like attachments) in a single click.

**Comment by peterchanws** [comment]
Fine with me.

**Comment by chinuhub** [comment]
@peterchanws By 'message body' do we mean the body of only that message or does it contain the messages from the same thread (in earlier replies) too ?

**Comment by peterchanws** [comment]
Ver epadd-standalone-v6-beta-13June.jar
Feature implemented

**Comment by peterchanws** [comment]
Archive: Bush full
After I click "EXPORT", it takes 18 min before the system prompt the zipped file will be downloaded to download location. We may need system message to let user know the system is working on generating the file.

**Comment by peterchanws** [comment]
Ver epadd-standalone-v6-beta21.jar
16GB RAM i7 8550 cpu
Bush full

Took 33 min to complete download.

**Comment by peterchanws** [comment]
Add message date for each message

**Comment by peterchanws** [comment]
"Message" in text file should be replaced by "Subject"
