### ISSUE TITLE
Search using terms in a file

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#225]
@hangal Do you think we can add this in this (ver 6) release?

Add "File Search" to Search page
![screen shot 2018-06-16 at 10 29 26 am](https://user-images.githubusercontent.com/1050899/41500972-5c4fce20-7150-11e8-8df2-604781767706.png)

In File Search Page
![screen shot 2018-06-16 at 10 29 18 am](https://user-images.githubusercontent.com/1050899/41500967-5508998a-7150-11e8-9b0e-f139d16ce877.png)

Results will be shown in message view

**Comment by peterchanws** [comment]
Only for appraisal, processing and delivery modules
No available in discovery module

**Comment by chinuhub** [comment]
What is the spec here? Is it the search of all messages which contain the terms specified in the given file?

**Comment by peterchanws** [comment]
Yes, it will be a full text search of all messages using the terms specified in a given file. 1 term per line. Term can include multiple words. Sudheendra said he would discuss with you tomorrow.

**Comment by peterchanws** [comment]
Result screen shows "Match Entities" Unmatched Entities".
Please change to "Match Term
![capture1](https://user-images.githubusercontent.com/1050899/41994765-69e5ff84-7a04-11e8-998a-4e94faa69740.PNG)
s" Unmatched Terms".

**Comment by peterchanws** [comment]
Terms in a line with multiple words should be searched as single term.
![capture](https://user-images.githubusercontent.com/1050899/42009930-48059248-7a41-11e8-9b33-98bd56861a37.PNG)

**Comment by peterchanws** [comment]
I still got hits which match part of the term. eg. term "neck pain", result: pain is highlighted
when I click pain, system search for "pain" not "neck pain" 
Can the system search "neck pin" instead of "pain"?

**Comment by peterchanws** [comment]
archive: Bush Full
search for "neck pain" using Simple Search produce 19 hits
search for the term neck pain using Term Search, the term "pain is highlighted, click"pain" got 3048 messages

**Comment by peterchanws** [comment]
This issue occurs when "pain" in "neck pain"exist as a term in itself. 
Improvement needed if possible.

**Comment by peterchanws** [comment]
Please update the language inside the Multi-term Search"
![capture1](https://user-images.githubusercontent.com/1050899/42117407-1c2f0fac-7bb1-11e8-9c93-d54776c12272.PNG)
change from 
....  select a highlighted entity......
to
....  select a highlighted term......

**Comment by chinuhub** [comment]
@peterchanws Issue #281 is the issue opened for the problem found in this feature. Apart from that this feature is done. It's better to keep only one github issue per feature/bug.
