### ISSUE TITLE
Make sure spell check is not running in ePADD tabs

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#23]
When spell check is running in the browser in editing correspondents for a large collections, system response time become extremely slow,

**Comment by vihari** [comment]
Just so that you know, the spell checker is not the only reason for non-responsive edit-correspondents page.

**Comment by vihari** [comment]
@peterchanws The spell checker is disabled, please test to see if the edit-correspondents page loads any faster.

**Comment by peterchanws** [comment]
Much faster now.
