### ISSUE TITLE
error when importing new accession to processing

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#234]
Ver beta1-2July
bush small
Win 10
![capture3](https://user-images.githubusercontent.com/1050899/42176112-bd585a28-7ddc-11e8-8d50-1bf4e3996c79.PNG)

**Comment by chinuhub** [comment]
I could not reproduce it in linux. Could you pleas upload the log file? Did you try it on mac?

**Comment by peterchanws** [comment]
@chinuhub 
I used the program to import archives created using previous version. Import is successful.
The error appears when I use archives created using v6-berta1-2July version.
