### ISSUE TITLE
dmg file defaulted to 64GB RAM run much slower than exe file with same amount of RAM

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#235]
Took 18 min to scan 1700 folders using epadd-standalone.jar
Took 18 min to scan 600 folders using dmg version packaged with 64GB RAM as default

**Comment by peterchanws** [comment]
JDK 1.81
dmg file with 64GB
Load correspondent: 5 sec; person entities: 48 sec

**Comment by peterchanws** [comment]
ver v6
jar file: Took 18 min to scan 1700 folders
Took 18 min to scan 600 folders using dmg version packaged with 64GB RAM as default

**Comment by peterchanws** [comment]
ver 6; MacBook Pro; 2 cores; 16GB RAM
Took 15:26 min to scan 1985 folders using epadd-standalone.jar 128GB RAM
Took 25:22 min to scan 1985 folders using dmg version packaged with 64GB RAM as default

**Comment by peterchanws** [comment]
ver 6, Mac mini; 16GB RAM; Terry Eudora
Took 4:09 min to scan 5230 folders using .dmg
Took  3:01 min to scan 5230 folders using .jar

**Comment by peterchanws** [comment]
v7 final Jan 22
It took ~6 hrs to index Terry (full) using exe build in a 32GB RAM machine
From task manager, Java use ~25GB RAM
![exe terry reading mbox 2](https://user-images.githubusercontent.com/1050899/51642301-94a71000-1f1d-11e9-96ab-f58888a59478.PNG)
It took much much longer to index the same archive using dmg build in a 32GB RAM machine

**Comment by peterchanws** [comment]
@hangal this show the dmg file didn't use as much ram as the exe file.

**Comment by peterchanws** [comment]
somehow system indicate 28 hrs to go after I started the indexing 10 hrs ago.
<img width="1135" alt="screen shot 2019-01-25 at 12 01 09 pm" src="https://user-images.githubusercontent.com/1050899/51769923-2be4a280-2099-11e9-9af7-e42f04b743e7.png">

**Comment by peterchanws** [comment]
another attempt to use dmg file to index Terry (full). System indicate 24 hrs to go after running for the job after 13 hrs. log file: ePADD 0127_0642

**Comment by peterchanws** [comment]
ver Jan 30, 2019
Indexing of Terry (Eudora) took 32 min using jar file. It took more than 3 hrs when I used the dmg file.

**Comment by icgifford** [comment]
Refers to outdated versions of software
