### ISSUE TITLE
Sort message by earliest date in message view by default in a set of messages

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#237]
Set of messages either come from search or browse are NOT presented not in chronological order. Users are more comfortable if the results are sorted and presented with the earliest message first.

**Comment by chinuhub** [comment]
With UI change a new option will be added on the message browse screen to sort messages.

**Comment by peterchanws** [comment]
Yes, the new UI proposed include the following options in message screen: 
Most relevant
Newest first
Oldest first

**Comment by chinuhub** [comment]
Now, by default the messages will be sorted by date.

**Comment by peterchanws** [comment]
feature added
