### ISSUE TITLE
Bag writing is slow resulting in a slower close/save operation

### ISSUE THREAD

**Issue by chinuhub** [ePADD/epadd#239]
Especially on windows 10 this difference is more prominent.

**Comment by chinuhub** [comment]
It seems that the manifestwriter class of bagit library repeatedly opens and close file handles when writing a set of manifests. This could be done differently by writing all manifests together and then closing them. See if this change can be made and then compare the performance difference.

**Comment by chinuhub** [comment]
After modifying the bag library the result is very promising. Earlier to write say 2000 entries in the manifest file the file was getting opened and closed 2000 times writing one entry each time. This resulted in a degrading performance while writing the manifest.

**Comment by peterchanws** [comment]
Issue fixed on July 19 version, however, issue appears again on July 20 version

**Comment by chinuhub** [comment]
Is this behaviour same on mac as well?

**Comment by peterchanws** [comment]
No

**Comment by peterchanws** [comment]
Can you test this on windows machine in your office?

**Comment by chinuhub** [comment]
@peterchanws Can you test this on windows machine in your office?

**Comment by peterchanws** [comment]
I tested this morning. It seemed much quicker. However, since it got "no JSON error" reported in #257 , I didn't the exact timing.

**Comment by peterchanws** [comment]
@chinuhub I re-index Terry in a Windows laptop with 16GB RAM, 4 core processors. It took 4 min before  the system to show the "no JSON" error. Please see log in Google Drive. Reopen the issue again.

**Comment by chinuhub** [comment]
@peterchanws After I fixed the 'no json erro' did you try it again?

**Comment by peterchanws** [comment]
Yes. It works


Peter Chan 

Digital Archivist

ePADD project Manager 

Stanford University Libraries 

Green Library, 557 Escondido Mall 

Stanford, CA  94305-6064 

(650) 924-2404 | pchan3@stanford.edu


________________________________

**Comment by peterchanws** [comment]
28July version 
Took 10 min to close Bush - full archive under Win 10
See log in Google Drive

**Comment by peterchanws** [comment]
ver 7 2 Oct
acceptable now
