### ISSUE TITLE
Rename "Query Generator" to "Multi-Entity Search"

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#240]

**Comment by hangal** [comment]
This seems confusing to me since we already have search for entities on the "adv. search screen".

**Comment by peterchanws** [comment]
@hangal 
Josh and I are working on the self-nomination of the PDC Preservation Award. We want to talk about "Query Generator". And then we thought "Entity Search" is a better term than "Query Generator". Do you have other suggestions?

**Comment by hangal** [comment]
I think some notion of "Bulk" or "Multi" has to be present.
Another root word could be "matcher" or "matching entities", because we are matching entities from one source to another.

**Comment by peterchanws** [comment]
What about "Multi-Entity Search"?
We have "Multi-Term" Search already.

**Comment by peterchanws** [comment]
Changed
