### ISSUE TITLE
The session gets closed on being idle for long

### ISSUE THREAD

**Issue by chinuhub** [ePADD/epadd#247]
Starting version 5 we no longer use session for archive but we still use session to store the resultset of the search result. That is used by 'export' and 'jog page' feature to find out the data set currently being rendered on browse page. However, if user remains idle for long and then continues browsing the messages then he might encounter error because the session would have been destroyed.

**Comment by peterchanws** [comment]
What can we do?

**Comment by hangal** [comment]
Yes, this is understood. We don't persist the dataset anywhere and probably doesn't make sense to.
We can tell users that the archive has been closed and ask them to reload the archive.

**Comment by peterchanws** [comment]
Could we do that for v6 final?

**Comment by peterchanws** [comment]
Cannot reproduce. Close for now.
