### ISSUE TITLE
Dump user understandable version of learnt model

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#25]
Vihari, can you dump out the NE model for the various types, in a format that can be easily reviewed?
We can use this to understand better how its working, see if there's a need to tune it, decide on cutoffs etc. Just switch the type numbers etc to the type names, and make it more explanatory.

**Comment by vihari** [comment]
I can give a dump of an understandable version of model in a file. Is that OK or you expect something more?

**Comment by hangal** [comment]
that's good for now.

**Comment by vihari** [comment]
@peterchanws @hangal The dump can be found here: http://muse.stanford.edu:9000/SequenceModelDump.tar.gz

**Comment by hangal** [comment]
ok, can you explain how to read this (and improve it further so that it is self-explanatory):

Token: School
ID: school
L[UNIVERSITY]:0.4-L[PLACE]:0.16-L[PERSON]:0.15-
R[EMPTY]:0.82-R[PLACE]:0.09-R[BUILDING]:0.02-
T[UNIVERSITY]:0.96-T[BUILDING]:0.03-T[ORGANISATION]:0-
SW[of]:0-SW[and]:0-SW[the]:0-
DICT[Y]:1-DICT[N]:0-
ADJ[N]:0.98-ADJ[Y]:0.02-
ADV[N]:0.98-ADV[Y]:0.02-
PREP[N]:1-PREP[Y]:0-
V[N]:1-V[Y]:0-
PN[N]:1-PN[Y]:0-
Evidence: 4041.0

**Comment by hangal** [comment]
2 questions about the locations file:
1. How come tokens like Lake/Mount (or even Indian/American/British from, say, Indian Ocean, American Samoa, etc.) are not in the Locations file?
2. Should we keep or drop the evidence 1.0 tokens? they seem like 1-offs.

Can you also sort the tokens in some fashion so its easier to browse the text file, e.g. by evidence.
