### ISSUE TITLE
Indexing of Attachments Not Consistent in Koch Archive

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#253]
NO ATTACHMENTS

version; July 20, 2018, epadd-standalone.jar
Platform: Win 10, 64GB RAM
![koch1](https://user-images.githubusercontent.com/1050899/43094595-3affc556-8e68-11e8-8fd0-904e28c0ad6a.PNG)

version; July 20, 2018, epadd-standalone.jar
Platform: Mac 10.13, 32GB RAM
<img width="1056" alt="screen shot 2018-07-23 at 3 00 58 pm" src="https://user-images.githubusercontent.com/1050899/43105330-546ccfd6-8e89-11e8-9470-7efdd945f16b.png">

version; July 19, 2018, epadd-standalone.jar
Platform: Win 10, 64GB RAM
![july19win](https://user-images.githubusercontent.com/1050899/43107666-fa9758c8-8e92-11e8-8631-74ac513a52ad.PNG)

**Comment by peterchanws** [comment]
WITH ATTACHMENTS

version; July 20, 2018, epadd-standalone.jar
Platform: Win 10, 64GB RAM

![july20win](https://user-images.githubusercontent.com/1050899/43167840-025df1da-8f50-11e8-8cbc-4367542df39c.PNG)

**Comment by peterchanws** [comment]
There are 2 sources of mail from Koch collection - one from Apple mail; one from Eudora mail.

The system didn't scan the 2 sources consistently.

**Comment by peterchanws** [comment]
@chinuhub Tested again at 10 am July 27. 
Mac 12GB RAM
Attachment not indexed
<img width="1125" alt="screen shot 2018-07-27 at 10 08 39 am" src="https://user-images.githubusercontent.com/1050899/43335968-112541f0-9185-11e8-9b11-9e5034085746.png">

**Comment by peterchanws** [comment]
@chinuhub Another test using Win desktop 64GB RAM, no attachment as well
![no-attachment](https://user-images.githubusercontent.com/1050899/43338214-9479b126-918a-11e8-9f9d-52483eb9187f.PNG)

**Comment by peterchanws** [comment]
Just finish indexing Terry using ver 20July, Win desktop 63GB RAM. No problem with attachment. So, may be the issue is the Koch data?
![terry](https://user-images.githubusercontent.com/1050899/43350338-385760c4-91bb-11e8-84da-effa2af02122.PNG)

**Comment by peterchanws** [comment]
@chinuhub I used different version of jar file to test the Koch archive and got the following results:

Use 18July version
1985 folders, 135057 incoming messages, 0 outgoing messages, 6568 image attachment
<img width="957" alt="koch 18july" src="https://user-images.githubusercontent.com/1050899/43375428-d050825c-9369-11e8-8d80-c227a690d9b1.png">

Use 28July version
>9000 folders, 56759 incoming, 85939 outgoing, 0 image attachment
<img width="951" alt="koch 28july" src="https://user-images.githubusercontent.com/1050899/43375754-d5f599a2-936b-11e8-9479-4187f020f132.png">

**Comment by peterchanws** [comment]
@chinuhub 
This issue is the top priority at this moment. We need to go back to donor asap.

**Comment by chinuhub** [comment]
@peterchanws Could you please test it with the latest release, on mac? I am also testing it on mac. Let us reconcile the result. I can see the attachments being downloaded now.

**Comment by peterchanws** [comment]
@chinuhub Does the 26Aug release fix the issue of missing some files?

**Comment by chinuhub** [comment]
@peterchanws No. It does not. The issue with mbox parsing seems more subtle.
