### ISSUE TITLE
Add what users input in the Import Screen to data report

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#254]
It would be useful as for audit if the system add what users input in the Import Screen to data report.

**Comment by chinuhub** [comment]
@peterchanws By 'what users input in the import Screen', what all fields of the import screen do you mean?

**Comment by chinuhub** [comment]
Name of email source is available only if mbox is specified as input. Is that fine?

**Comment by peterchanws** [comment]
feature added
