### ISSUE TITLE
Don't Show System Labels in Discovery Module 

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#260]
@chinuhub 
28July version, Discovery module
<img width="1114" alt="screen shot 2018-07-29 at 9 05 29 pm" src="https://user-images.githubusercontent.com/1050899/43377064-5347f394-9373-11e8-9d70-481fe79d29cf.png">

<img width="1138" alt="screen shot 2018-07-29 at 9 19 09 pm" src="https://user-images.githubusercontent.com/1050899/43377368-17caa828-9375-11e8-9750-604426326429.png">

Don't show "Reviewed" and "Cleared for Release" label

**Comment by peterchanws** [comment]
@chinuhub 
Is this an easy enhancement? If yes, we can bundle with v6.1.

**Comment by hangal** [comment]
it should be easy.
also, do we need cleared for release in appraisal?

**Comment by chinuhub** [comment]
In current setup, only DNT and CFR are system labels. Reviewed is provided by default but is not a system label as such. 
@hangal  One simple way to achieve this is by not transferring these labels in the label description file to discovery and delivery.

**Comment by hangal** [comment]
@chinuhub can you pls fix it and then we will release 6.1 tomorrow.

**Comment by chinuhub** [comment]
Fixed and uploaded a build. Now system labels (CFR and DNT) will not be shown in discovery and delivery modules. Please confirm if that is the expected behavior.

**Comment by peterchanws** [comment]
@chinuhub 
CFR and DNT were removed.
Could we also remove "Reviewed" in Delivery and Discovery?

**Comment by peterchanws** [comment]
@chinuhub Sorry, Chinmay. By removing "Reviewed" in Discovery & Delivery modules, I meant removing only the "Reviewed" label assigned to messages, if any. The "Reviewed" label is still available to users in Delivery module (not on Discover). Please let me know if you are not clear.

**Comment by peterchanws** [comment]
@chinuhub Thanks for the detail spec. These are what I want.

**Comment by chinuhub** [comment]
@peterchanws Uploaded the test build.

**Comment by peterchanws** [comment]
@chinuhub  Can't find the test build.

**Comment by chinuhub** [comment]
@peterchanws Modified the same 10 Aug build.

**Comment by peterchanws** [comment]
@chinuhub no build in 10 Aug draft

**Comment by chinuhub** [comment]
@peterchanws Uploaded again. I don't know why it did not get saved.

**Comment by peterchanws** [comment]
works fine
