### ISSUE TITLE
Got Error code:null type: null when indexing Bush - full (Mac)

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#261]
28July version, Full Bush, Mac
see log in Google Drive

No problem indexing using 20July, v6 beta1 and v5.1 versions of the program.

**Comment by peterchanws** [comment]
No problem under Win 10
Start testing on another Mac

**Comment by peterchanws** [comment]
@chinuhub Got same error message "Error code:null type: null" using another Mac.
See log in Google drive

**Comment by chinuhub** [comment]
@peterchanws Can you please check if this file '/ePADD6/epadd-appraisal/user/data/blobs/28511.Pretty Park.exe' is there or not? There is an exception thrown when trying to open this file.

**Comment by peterchanws** [comment]
28511.Pretty Park.exe is not in the blobs folder in Mac.

**Comment by peterchanws** [comment]
Got "no JSON was returned!" when using MacPro in the lab indexing full Bush; terminal terminate by system
See log in Google Drive

**Comment by peterchanws** [comment]
I used the 20July, 18July, v6beta1 and V51 to run the same full Bush in the same machine. If the anti-virus software cannot catch the virus, it should behave the same under different epadd versions. Virus in the Bush archive is a known facts. We encountered them every time we run the full Bush archive.

**Comment by chinuhub** [comment]
In the blobs folder of those archive (Bush full indexed by 20July or 18July version) do you see a file named 'Happy99.exe'? Or is there any exe file in that folder?
That archive must have been 'indexed' by 20th July or 18th July version.

**Comment by peterchanws** [comment]
No, Happy99.exe doesn't exist in the blobs folders indexed using 20July, v6beta1 or 28July epadd versions.


Are you available for a chat now?


Peter


Peter Chan 

Digital Archivist

ePADD project Manager 

Stanford University Libraries 

Green Library, 557 Escondido Mall 

Stanford, CA  94305-6064 

(650) 924-2404 | pchan3@stanford.edu


________________________________

**Comment by chinuhub** [comment]
Yes. I am on appear.in

**Comment by peterchanws** [comment]
me too, but can't see you


Peter Chan 

Digital Archivist

ePADD project Manager 

Stanford University Libraries 

Green Library, 557 Escondido Mall 

Stanford, CA  94305-6064 

(650) 924-2404 | pchan3@stanford.edu


________________________________

**Comment by peterchanws** [comment]
Reminded users to set anti-virus software to kill or delete virus without user intervention.
