### ISSUE TITLE
Take long time to switch lexicons

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#266]
ver 6, epadd-standalone.jar with 16GB RAM
MacBook Pro 16GB RAM, 2-core processor
Bush full
Took 28 seconds to switch from browse-top screen to lexicon home
Took 3 min 20 sec to switch from General lexicon to Sensitive lexicon

**Comment by chinuhub** [comment]
This should be improved in the latest build added on 24th Sep.

**Comment by peterchanws** [comment]
@chinuhub 
cannot find build on 24th Sep draft

**Comment by peterchanws** [comment]
ver v7 26 Sep
Great response time.
