### ISSUE TITLE
Exclude messages without dates in visualization

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#27]
Exclude messages without dates in visualization.
Provide link to access undated messages.

**Comment by hangal** [comment]
Peter, which archive does this occur in?

**Comment by peterchanws** [comment]
In Creeley. Also, in other achives with messages without dates.

**Comment by peterchanws** [comment]
Should be fixed already. Need to check.

**Comment by hangal** [comment]
Think this is already fixed.

**Comment by peterchanws** [comment]
Yes.
