### ISSUE TITLE
Unexpected error on gmail data in Data Reports

### ISSUE THREAD

**Issue by SachinSalunke** [ePADD/epadd#270]
![summary_error_msg](https://user-images.githubusercontent.com/42311769/43999544-cfac9166-9e2b-11e8-9908-0b683deb0d9c.jpg)
 
In my gmail takeout file I see this errors.

**Comment by hangal** [comment]
this is not easy to reproduce now. we'll keep an eye out for similar issues in the future.
closing for now.
