### ISSUE TITLE
Making correspondents listing and editing robust

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#272]
Scenario: @peterchanws by mistake uploaded Koch address book into Bush email archive. The correspondents table went blank. But if an email address is not in the address book, it should still be considered like a virtual, independent contact.

Recommendation:
1. When an address book is uploaded, it can give overview stats like:
"500 correspondents read, 469 are associated with at least one message, 31 not with any message. 43 email addresses are in the archive but not in this address book."

2. Uploading address book should give an error message if the same email addresses is in multiple email addresses.
 
3. In the correspondent listing, if an email address is not in the address book, it should be listed as one contact.

**Comment by icgifford** [comment]
Improved through Palladium work
