### ISSUE TITLE
File Size Filter in Other Attachments Not Working in Processing and Delivery Module

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#274]
Archive ID missing in the search,

**Comment by hangal** [comment]
@chinuhub archiveID doesn't seem to be included in the URL params when the filter is applied.

**Comment by chinuhub** [comment]
@peterchanws Which page is this? Advanced search or attachments?

**Comment by peterchanws** [comment]
@chinuhub In "Other Attachments"

**Comment by peterchanws** [comment]
23-Aug-v6.1
issue fixe
