### ISSUE TITLE
Archive dir. should be locked during indexing

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#275]
We came across a scenario where 2 tabs are open on /epadd/folders.
Pressing continue on both will start indexing in both tabs.
can we lock the archive folder just for importing email?

**Comment by hangal** [comment]
Another scenario:
user is doing export (say from appraisal)
by mistake they reload the page.
This will probably cause a fresh export to be kicked off (?).
We should not allow this situation to happen.

**Comment by icgifford** [comment]
Recommended detailing in user guide
