### ISSUE TITLE
Issue an error message if not using 64b java

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#276]
Sachin tried to launch epadd.exe v6.0 with a 32b installation of java.
It failed during importing his gmail takeout file.
It probably silently failed to use 64gb mem and reverted to the default.

we should check internally within epadd and refuse to launch if if it's not a 64b jre.

**Comment by hangal** [comment]
We need to try and reproduce this with a 32b install of Java.
May need java 8 - https://jdk.java.net/java-se-ri/8-MR3

**Comment by icgifford** [comment]
Refers to older versions of software
