### ISSUE TITLE
Folder listing page should have file size

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#284]
Now that we're moving to a table view for the folders, it would be good to have a column indicating file size. So there could be 3 columns in the table: file name, # messages and file size.
It should be possible to sort by the file size.
File size preferably should not more than 3 significant digits and abbreviated to KB/MB.

**Comment by peterchanws** [comment]
Feature not appear in ver 6.1 final

**Comment by peterchanws** [comment]
v7 26Sep
file size not appear in the column

**Comment by peterchanws** [comment]
v7 Jan 17
Existing format should be changed to specification dated Aug 16, 2018 or remove "Incoming" and "Outgoing"

**Comment by peterchanws** [comment]
Done
