### ISSUE TITLE
Show dates for first and last occurrence of entities 

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#29]
![fine grain](https://cloud.githubusercontent.com/assets/1050899/12680150/19c49f68-c65d-11e5-939d-ce372a23747c.png)

Scores: needed
Time: not needed
Mention - replace by "Hits"
Entities: person, organization, location and other fine type entities

**Comment by hangal** [comment]
@peterchanws Need to discuss UI about showing this information.
Where to show it?
In simple columns?
Maybe in small font below the entity name?
Show the range graphically?

**Comment by peterchanws** [comment]
ProdPad Idea #41
