### ISSUE TITLE
Search on Merged Entities give results of only one entity.

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#297]
ver 6 sep 13
Before I I merged the entities "Jeb Bush" and "Frank Brogan", 
Browse Entity page show:
Jeb Bush 770 messages
Frank Brogan 19 messages
When I click "Jeb Bush", message page show:
Search 
"Jeb Bush" (899)

After I merged the entities "Jeb Bush" and "Frank Brogan", 
Browse Entity page show: 
Jeb Bush 780 messages
NO Frank Brogan
When I hop over "Jeb Bish", system show Alternate names: "Jeb Bush" and "Frank Brogan"
When I click "Jeb Bush", message page show:
Search 
"Jeb Bush" (899)

System should search BOTH "Jeb Bush" and "Frank Brogan"

**Comment by hangal** [comment]
Let us discuss the spec for this as one of the agenda items in tomorrow's
meeting.

**Comment by peterchanws** [comment]
v7 6 Oct
works fine

**Comment by peterchanws** [comment]
v7 12Oct Bush small
not working again

**Comment by peterchanws** [comment]
v7 15Oct
not fix yet

**Comment by peterchanws** [comment]
fixed
