### ISSUE TITLE
Images not carried over to processing module from appraisal module under Win 10

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#299]
ver 6.1 final; 
Mac OS 10.14, Bush (small) dmg, jar files; Firefox, Chrome
System response "Unable to import accession: null" when import collection to processing module.
Works fine under Mac OS 10.13
Windows 10 exe file
Only the profile photo is transferred; landing and banner photos are not transferred to processing module

**Comment by peterchanws** [comment]
@chinuhub 
Tried New Incognito windows in Chrome under Win 10. Still have the same problem:
Only the profile photo is transferred; landing and banner photos are not transferred to processing module
Could you reproduce in your environment?

**Comment by peterchanws** [comment]
Mac OS 10.14, Bush (small) dmg file, Chrome
works fine in another machine.

**Comment by peterchanws** [comment]
landing and banner photos are not transferred to processing module using another Win 10 machine (3 in total)

**Comment by chinuhub** [comment]
@peterchanws  I could not reproduce it. Could you please send me the log file (for export to processing operation)?

**Comment by peterchanws** [comment]
Tested again just now. Log uploaded to Google Drive Github issue

**Comment by peterchanws** [comment]
ver v6 sep 16
images not appear
