### ISSUE TITLE
v7 - Lexicon Result page not match with test category result

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#301]
v7
0 hits for "Crime" category; many hits for terms defined in the "Crime" category

murder | 5245
fraud | 3149
probation | 2177
harassment | 2134
solicit | 1992
assault | 1655
vandalism | 1552
rape | 1141
theft | 1073

**Comment by chinuhub** [comment]
There is a typo in the lexicon file for these categories. Two words - "tax evasion" and "maria pastora" are missing the matching quotation marks.

**Comment by peterchanws** [comment]
ver v7 2 Oct
still 0 hits after adding " to "tax evasion" and "maria pastora"

**Comment by peterchanws** [comment]
ver v7 6Oct
issue fixed
