### ISSUE TITLE
Got error when exporting to processing module

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#305]
An archive made up of full TW and Bush
ver 2 Oct
See logion in Github

**Comment by peterchanws** [comment]
Able to goto browse-top, but attachments missing from the index
![capture2](https://user-images.githubusercontent.com/1050899/46575410-6d760400-c969-11e8-9c8f-8f1f9b035c24.PNG)

**Comment by peterchanws** [comment]
v7 12 Oct
Still not working

**Comment by peterchanws** [comment]
still the same after clearing the cache

**Comment by chinuhub** [comment]
The log shows that the error occurred due to insufficient memory. We need to relook at Indexer.java::getAllDocsWithField method. This one iterates over all docs in index and store an in-memory representation of live docs.

**Comment by peterchanws** [comment]
ver 7 beta 1
Messages: 1,092,943 
Windows 10; 32GB ram allocated
export to processing - success
import to processing - success
export to delivery - success
export to discovery - hang for several hrs

**Comment by peterchanws** [comment]
ver7 beta 2 - public
Win 10, 16GB RAM. 6 core processor
archive Terry + Fikes + Bush
system didn't show dashboard page after finishing indexing
error saying not enough ram during export to processing 
see log in Google drive

**Comment by peterchanws** [comment]
v7 Jan 11
No such message when export to processing for Terry+Fikes+Bush
close issue
