### ISSUE TITLE
Entity editing overwriting when edited from different type page (Person/Place/ etc.)

### ISSUE THREAD

**Issue by chinuhub** [ePADD/epadd#307]
Steps to reproduce:
1. Open 'Person Entity', go to 'Edit', Combine a few and save.
2. Open 'Other Entities', go to 'Place', Combine a few and save.

The latter one overwrites the grouping done for 'Person' entities.
Expected behavior:
Both should be present in the file 'EntityBook' with appropriate entity type mentioned in the record.

**Comment by peterchanws** [comment]
v7 6 Oct
not able to test because system doesn't response to click on entities
