### ISSUE TITLE
Merge / correct extracted entities

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#31]
Users type the preferred name of entities and the entities to be included in a text file for relative entity types.
Users update kill list of relative entity types for entities recognized by system.

**Comment by glynnedw** [comment]
Or users could select two entities to merge > and choose which one is preferred?
Having a kill list is good - for things like "God Bless" that show up in the NER for Jeb Bush's archive; but not when you have multiple versions of an entity

**Comment by peterchanws** [comment]
ProdPad Idea #43
