### ISSUE TITLE
Error when exporting unprocessed attachments with extensions in processing module

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#313]
v7 10 Oct Bush full

Exporting Only Unprocessed attachments with extensions: pages;doc;docx

0 attachments exported to /Users/Peter Chan/Desktop/epadd/.
9 errorsoccurred.

Errors: #1. Dec 2 Amanda comin...e.doc | May 06 2002 | 12KB
Error exporting blob: \Users\Peter Chan\Desktop\epadd\file:_C:_Users_Peter%20Chan_epadd-processing_ePADD%20archive%20of%20Jeb%20Bush%20-%20full%20-%20v7%2010oct_data_blobs_946.%231.%20Dec%202%20Amanda%20coming%20here.doc (The filename, directory name, or volume label syntax is incorrect)

Politica.DOC | Feb 05 2000 | 24KB
Error exporting blob: \Users\Peter Chan\Desktop\epadd\file:_C:_Users_Peter%20Chan_epadd-processing_ePADD%20archive%20of%20Jeb%20Bush%20-%20full%20-%20v7%2010oct_data_blobs_5166.Politica.DOC (The filename, directory name, or volume label syntax is incorrect)

Polk Co_.doc | Mar 30 2001 | 21KB
Error exporting blob: \Users\Peter Chan\Desktop\epadd\file:_C:_Users_Peter%20Chan_epadd-processing_ePADD%20archive%20of%20Jeb%20Bush%20-%20full%20-%20v7%2010oct_data_blobs_7460.Polk%20Co_.doc (The filename, directory name, or volume label syntax is incorrect)

GovBushWin2.doc | Jul 05 2001 | 37KB
Error exporting blob: \Users\Peter Chan\Desktop\epadd\file:_C:_Users_Peter%20Chan_epadd-processing_ePADD%20archive%20of%20Jeb%20Bush%20-%20full%20-%20v7%2010oct_data_blobs_8421.GovBushWin2.doc (The filename, directory name, or volume label syntax is incorrect)

GovBushWordMac.doc | Jul 05 2001 | 35KB
Error exporting blob: \Users\Peter Chan\Desktop\epadd\file:_C:_Users_Peter%20Chan_epadd-processing_ePADD%20archive%20of%20Jeb%20Bush%20-%20full%20-%20v7%2010oct_data_blobs_8422.GovBushWordMac.doc (The filename, directory name, or volume label syntax is incorrect)

grandjury.doc | Aug 14 2001 | 9KB
Error exporting blob: \Users\Peter Chan\Desktop\epadd\file:_C:_Users_Peter%20Chan_epadd-processing_ePADD%20archive%20of%20Jeb%20Bush%20-%20full%20-%20v7%2010oct_data_blobs_8691.grandjury.doc (The filename, directory name, or volume label syntax is incorrect)

C1_April2003_report.doc | Apr 18 2003 | 451KB
Error exporting blob: \Users\Peter Chan\Desktop\epadd\file:_C:_Users_Peter%20Chan_epadd-processing_ePADD%20archive%20of%20Jeb%20Bush%20-%20full%20-%20v7%2010oct_data_blobs_11977.C1_April2003_report.doc (The filename, directory name, or volume label syntax is incorrect)

Due Process Hearing Re...4.doc | Feb 12 2004 | 74KB
Error exporting blob: \Users\Peter Chan\Desktop\epadd\file:_C:_Users_Peter%20Chan_epadd-processing_ePADD%20archive%20of%20Jeb%20Bush%20-%20full%20-%20v7%2010oct_data_blobs_14318.Due%20Process%20Hearing%20Request%20-%2001-08-04.doc (The filename, directory name, or volume label syntax is incorrect)

Second Due Process Hea...4.doc | Feb 12 2004 | 79KB
Error exporting blob: \Users\Peter Chan\Desktop\epadd\file:_C:_Users_Peter%20Chan_epadd-processing_ePADD%20archive%20of%20Jeb%20Bush%20-%20full%20-%20v7%2010oct_data_blobs_14319.Second%20Due%20Process%20Hearing%20Request%20-%2001-26-04.doc (The filename, directory name, or volume label syntax is incorrect)

**Comment by peterchanws** [comment]
v7 12Oct
same after clearing cache
'
<img width="770" alt="capture" src="https://user-images.githubusercontent.com/1050899/46892291-84958400-ce8a-11e8-812a-02902b222777.PNG">

**Comment by chinuhub** [comment]
This appears only on windows.
