### ISSUE TITLE
Search for messages dated 1960/01/01 return all messages

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#32]

**Comment by vihari** [comment]
I can replicate this, thanks.

**Comment by peterchanws** [comment]
Version Feb 19
Win 10 Bush Small
There is 1 message with date 1960/01/01; However, search for message with date 1960/01/01 get NO result.
![capture1](https://cloud.githubusercontent.com/assets/1050899/13190593/de27057e-d712-11e5-8a71-b1dfa836ab04.PNG)

**Comment by vihari** [comment]
That is strange, I tested it with Creeley-small which has around three messages with no date and search for 1960 gave the correct result.
I will check it with Bush-small.
Just to confirm, you are searching 1960 in the date field, right? I mean "From date" 1960/01/01 and "End date" empty.

**Comment by peterchanws** [comment]
I put 1960/01/01 in the end filed as well. 
If I let it empty, I got 1 hit.

**Comment by vihari** [comment]
When you put 1960/01/01 in the "end date" as well, the search is ill-defined. Returning no hits in this case is not what you would expect?

**Comment by peterchanws** [comment]
Even if I put 1960/01/31 or 1960/12/31, there is no hit.
However, if I put start date "1970/01/01" end date "1970/12/31", I got a hit for a messages with date 1970/01/15. It is not consistent. Having said that we plan to have a link to all messages with no date.

**Comment by peterchanws** [comment]
Issue closed. Will create UI for when to put the link to all undated messages.
