### ISSUE TITLE
quotedPrintable throwing exception when exporting messages to mbox

### ISSUE THREAD

**Issue by chinuhub** [ePADD/epadd#327]
When exporting messages to mbox the following possibilities exist for content and the attachments. Based on these cases we chose charset and the encoding.

   Content .        ContentCharSet    ContentEncoding .      
1.  ASCII                 UTF-8                   quotedprintable      
2.  I18N                  UTF-8                    base64

Attachments, if present, will be encoded using base64 and corresponding content type.

Before exporting, the message content and the attachment will be encoded as specified above.

**Comment by peterchanws** [comment]
only during download from message view
