### ISSUE TITLE
Addressbook computation algorithm change: Spec

### ISSUE THREAD

**Issue by chinuhub** [ePADD/epadd#338]
Provide a set of email addresses as trusted one.

1. When processing a message:
	If sender is a trusted mail address-
		Call process contact with all name-email pairs (appearing anywhere in this message’s header) as trusted ones.
	if sender is not a trusted email address-
		Call process contact with all name-email pairs (appearing anywhere in this message’s header) as non-trusted ones.

If non-trusted name-email pair then don’t do unification based on name (but the unification based on email is still done). After that, just add the name in the contact.

If trusted name-email pair then perform the unification as done earlier.

**Case 1.**

Suppose we have two name-email pairs appearing in the archive.
**Fikes <notification@linkedin.com>** and  **Moore <notification@linkedin.in>**

Earlier these two were being unified because of the common mail id. As a result, these two different names were being put in the same contact. It resulted in those names being in the same contact with proper names of Fikes like 
Richard Fikes
Richard L. Fikes
Fikes 
fikes@cs.stanford.edu.in

After the algorithm change,  now there will be a new contact with email id as notification@linkedin.com and names of **Fikes**, **Moore** etc. being together in that contact.

** Case 2 **
[Not addressed in modified algorithm] if someone sends a mail to 

Dummy <fikes@cs.stanford.edu> and fikes@cs.stanford.edu is a trusted email address:

**If this mail was sent from a trusted name-email pair:**
    Then this association is a trusted one and unification will be based on ‘dummy’ as well as on email address.
 **If this mail was sent from a non-trusted name-email pair:**
	Then this association is non-trusted so no unification will take place based on "dummy" but unification will take place based on email. It results in "dummy" being added to the contact where fikes@cs.stanford.edu is a valid email address.

**Comment by peterchanws** [comment]
Using Bush small and jeb@jeb.org initially, I got Jeb Bush listed in the correspondent list. However, after adding jeb@bush-brogan-2002 as trusted email address, Jeb Bush disappear from the correspondent list. Will continue testing with Fikes.

**Comment by peterchanws** [comment]
Case 1: User doesn't know the main email address 
Case 2: User input a trusted email address which has only incoming messages
Case 3: User input a trusted email address which has outgoing messages

Case 1: User doesn't know the main email address 
This happens when

**Comment by peterchanws** [comment]
ver Jan 16
The 3 columns should apply to processing, discovery and delivery module as well as appraisal.

**Comment by peterchanws** [comment]
Add "Archive owner email address" under "More". Although we can add this information in Edit Correspondent, our system (via browser) is not good at editing a big address book.

**Comment by peterchanws** [comment]
System somehow treats some email as correspondent name. Example:

brankel@eog.state.fl.us
Laura Branker
Branker, Laura
laura.branker@myflorida.com

**Comment by peterchanws** [comment]
It seems "Received messages" count messages "To" the designated address. It should include "cc/bcc" as well.

**Comment by peterchanws** [comment]
Need to update Advance Search:
From:
Messages Direction: Incoming; Outgoing; Either
To: 
Messages Direction: Sent; Received; Either

**Comment by peterchanws** [comment]
Need to update "Information about this archive"
from 
Messages:  123
Incoming: 234
Outgoing: 345
---
Images: 234
Documents: 345
Others:456

to 
Messages: 123
Images: 234
Documents: 345
Others:456

![screen shot 2019-01-17 at 6 15 01 pm](https://user-images.githubusercontent.com/1050899/51364034-72317480-1a8f-11e9-9926-b73b8e9de590.png)

**Comment by hangal** [comment]
Should we have 2 fields?

Total Messages
Messages sent by archive owner

**Comment by peterchanws** [comment]
Archive: Bush small

When I change archive owner from Jeb Bush to Laura Banker, message counts didn't reflect such change:
![screen shot 2019-01-17 at 10 16 00 pm](https://user-images.githubusercontent.com/1050899/51368739-7d8f9a80-1aa5-11e9-9373-c79bb3bce459.png)

**Comment by chinuhub** [comment]
Did you make sure that the same mail id did not appear in more than on contact?

**Comment by peterchanws** [comment]
@chinuhub Sorry. After further verification, message counts after changes in email owner are correct.

**Comment by peterchanws** [comment]
feature added
