### ISSUE TITLE
System to open messages in Debug Correspondents in a set

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#346]
ver Jan 16
ePADD now opens a page where a list of messages by message id are display for viewing one by one

It would be much better if users can click the xx messages link in the Debug messages page and the system will open a tab with all relative messages.
<img width="1251" alt="screen shot 2019-01-16 at 9 26 31 am" src="https://user-images.githubusercontent.com/1050899/51266890-46b86800-1971-11e9-8aea-d12e4e262578.png">
<img width="617" alt="screen shot 2019-01-16 at 9 26 21 am" src="https://user-images.githubusercontent.com/1050899/51266900-4ae48580-1971-11e9-8742-f65395c6a7be.png">

**Comment by hangal** [comment]
Peter, I suggest we defer niceties like this.
We are making very late breaking changes and I am very worried about
stability of the 7.0 final.
Let us focus on extensive testing of the existing features.

**Comment by peterchanws** [comment]
features added
