### ISSUE TITLE
Cross Collection Search Not Working

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#349]
ver Jan 22, dmg file (discovery module)
Got hits for search term "god" in 2 different collections. However, there is no hit when I perform the same search under cross collection search.

**Comment by hangal** [comment]
Cross-collection search is only for entities. "god" is not an entity. (um,
unless you treat Him respectfully.)

**Comment by peterchanws** [comment]
but I got hits from both in discovery module

**Comment by peterchanws** [comment]
try New York, have hits on 2 collections individually, but not in cross collection search

**Comment by peterchanws** [comment]
ver Jan 23
clear cache before testing; still no hits

**Comment by peterchanws** [comment]
ver Jan 24
works now

**Comment by peterchanws** [comment]
In one of the 3 collections in discovery module, the matching terms in the messages are not highlighted.

**Comment by peterchanws** [comment]
ver Jan 28
the ones not highlighted are correspondents
leave enhancement on highlighting to next release
