### ISSUE TITLE
Advanced Search - autocomplete for correspondents with same name (e.g. Pat Hayes)

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#356]
ver Jan 29; Fikes (full)
Search for messages under Correspondents for "Pat Hayes" resulted 3993 messages.
The 3993 messages include results from ALL 14 different "Pat Hayes". How can users search one of the 14 "Pat Hayes" in Advanced Search?

**Comment by peterchanws** [comment]
I remember we talked about giving users the control if they want the system to auto expand the entered correspondent OR have an EXACT match of what is being entered in the field. What about adding a check box "do not expand entered email address" under "Name or email" in Advanced Search?
If we don't do that, if there are more than one correspondent with the same name, the search results are wrong.

**Comment by hangal** [comment]
We'll need a new path in the advanced search backend.
