### ISSUE TITLE
Messages not downloaded from Gmail A/c

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#36]
Version Jan 14, 2016
Try to download  harrisonstudio.aol@gmail.com
Authentication completed successfully but not message appear in the browse screen.
<img width="728" alt="screen shot 2016-01-21 at 12 50 45 pm" src="https://cloud.githubusercontent.com/assets/1050899/12494239/e9715100-c03d-11e5-8ffe-e80a27759776.png">
<img width="1057" alt="screen shot 2016-01-21 at 12 50 35 pm" src="https://cloud.githubusercontent.com/assets/1050899/12494241/eb402632-c03d-11e5-8b5e-0f8271e65e45.png">

**Comment by hangal** [comment]
Thanks for reporting this. Should be fixed in the next release.

**Comment by peterchanws** [comment]
Version 01282016
Not working. See debug log:

29 Jan 08:07:11 JSPHelper INFO - COMPLETED Request[user@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/ajax/doFetchAndIndex.jsp params: folder -> {epadd3@gmail.com^-^INBOX,epadd3@gmail.com^-^Trash,epadd3@gmail.com^-^[Gmail]/All Mail,epadd3@gmail.com^-^[Gmail]/Drafts,epadd3@gmail.com^-^[Gmail]/Important,epadd3@gmail.com^-^[Gmail]/Sent Mail,epadd3@gmail.com^-^[Gmail]/Spam,epadd3@gmail.com^-^[Gmail]/Starred,epadd3@gmail.com^-^[Gmail]/Trash,epadd3@gmail.com^-^[Gmail]/c812a76d.mbox.txt,} period -> Monthly downloadAttachments -> true link: http://localhost:9099/epadd/ajax/doFetchAndIndex.jsp?folder=epadd3@gmail.com^-^INBOX&folder=epadd3@gmail.com^-^INBOX&folder=epadd3@gmail.com^-^INBOX&folder=epadd3@gmail.com^-^INBOX&folder=epadd3@gmail.com^-^INBOX&folder=epadd3@gmail.com^-^INBOX&folder=epadd3@gmail.com^-^INBOX&folder=epadd3@gmail.com^-^INBOX&folder=epadd3@gmail.com^-^INBOX&folder=epadd3@gmail.com^-^INBOX&period=Monthly&downloadAttachments=true&
29 Jan 08:07:11 JSPHelper INFO - CLIENT LOG: Response text: {"resultPage":"error","error":"Exception fetching/indexing emails","status":1}
29 Jan 08:07:11 JSPHelper INFO - CLIENT LOG: j:[object Object]
29 Jan 08:07:11 JSPHelper INFO - NEW Request[user@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/error link: http://localhost:9099/epadd/error?
29 Jan 08:07:11 JSPHelper INFO - CLIENT LOG: Error in operation:{"resultPage":"error","error":"Exception fetching/indexing emails","status":1}
29 Jan 08:07:11 JSPHelper WARN - Error page reached. code:null message:null type: null
29 Jan 08:07:11 JSPHelper INFO - COMPLETED Request[user@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/error link: http://localhost:9099/epadd/error?
29 Jan 08:07:44 JSPHelper INFO - NEW Request[user@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/settings link: http://localhost:9099/epadd/settings?
29 Jan 08:07:44 JSPHelper INFO - COMPLETED Request[user@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/settings link: http://localhost:9099/epadd/settings?
29 Jan 08:07:52 JSPHelper INFO - NEW Request[user@0:0:0:0:0:0:0:1]: http://localhost:9099/epadd/debug link: http://localhost:9099/epadd/debug?

**Comment by hangal** [comment]
Sorry, looks like a Windows only error. Will fix in the next release.
Thanks for reporting.

Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
at java.util.regex.Matcher.appendReplacement(Unknown Source)
at java.util.regex.Matcher.replaceAll(Unknown Source)
at java.lang.String.replaceAll(Unknown Source)
at edu.stanford.muse.Config.getResourceAsStream(Config.java:74)
at edu.stanford.muse.util.NLPUtils.<clinit>(NLPUtils.java:35)
... 31 more

**Comment by peterchanws** [comment]
Got error under Mac as well.

**Comment by peterchanws** [comment]
Version 01/28/2016
See attached log for error.
[ePADD Log01282016.pdf](https://github.com/ePADD/epadd/files/132835/ePADD.Log01282016.pdf)

**Comment by hangal** [comment]
looks like the models are not in the right place:
16 Feb 08:14:06 JSPHelper ERROR - Could not load NER model from: SeqModel.ser

Can you try moving the files to be so:

under epadd-settings, there should be 3 files:
SeqModel.ser 
instance_types_2014-04.en.txt.bz2 
presetqueries.txt
(and 1 directory called models)

under epadd-settings/modelsmodels there should be 4 files
en-chunker.bin		
en-pos-maxent.bin	
en-sent.bin		
en-token.bin

Can you pls set up as above, clear your epadd-appraisal folder, and retry?
Sorry for the confusion -- things are in some flux over the exact format of the settings folder.

@vihari fyi

**Comment by peterchanws** [comment]
I don't have 

instance_types_2014-04.en.txt.bz2 

(and 1 directory called models)
under epadd-settings/modelsmodels there should be 4 files
en-chunker.bin
en-pos-maxent.bin
en-sent.bin
en-token.bin

Could you send me these files?

**Comment by hangal** [comment]
you should already have them, but they might be under a sub-folders called resources. Can you can move them over?

Also, pls download
http://suif.stanford.edu/~hangal/epadd/instance_types_2014-04.en.txt.bz2
and put it in the epadd-settings folder.

**Comment by peterchanws** [comment]
I don't have the resources folder. See
![screen shot 2016-02-16 at 6 10 32 pm](https://cloud.githubusercontent.com/assets/1050899/13097737/acf2b6a6-d4d8-11e5-9d14-f3a6dc7aed2b.png)

**Comment by hangal** [comment]
ok, could you pls download it from http://suif.stanford.edu/~hangal/epadd/models.zip
unzip into your epadd-settings folders, so the 4 files are in 
epadd-settings/models

**Comment by peterchanws** [comment]
Version Jan 26 (Feb 18)
Fixed
