### ISSUE TITLE
mboxs downloading with encoding errors on new line, curly quotes

### ISSUE THREAD

**Issue by sshipley64** [ePADD/epadd#363]
While messages appear in ePADD modules correctly,  when downloaded to an mbox file, new lines and curly quotes appear encoded and I have to run a script with the following to correct:

replace(b'=0A=0A', b'\n')
replace(b'=0A', b'\n')
replace(b'=92', b"'")
replace(b'=93', b'"')
replace(b'=94', b'"')

**Comment by hangal** [comment]
Thanks for the report. We have not seen this before.
Does it happen for you on every dataset or just sometimes?
is it possible to send us the data?

**Comment by sshipley64** [comment]
It’s not every email, but a major chunk of each account I've uploaded so far.  I've added an example of a folder as the mbox folder uploaded to epadd accession module and the same folder downloaded as a mbox from the delivery module.   

[https://drive.google.com/open?id=1m8VHVZYJUGKjzbiDiPEwGNjv8iKLUBdz](url)

**Comment by hangal** [comment]
@chinuhub will test this.

**Comment by tomhigginsuom** [comment]
We think this is because exporting to mbox encodes the data using Quoted-Printable - to be checked.
