### ISSUE TITLE
Exception fetching/indexing emails error with mbox exported from gmail

### ISSUE THREAD

**Issue by kieranjol** [ePADD/epadd#364]
On windows 10 with the latest release of ePADD - we have been unable to import mboxes when specifying the full path of the mbox or the folder containing multiple mbox files.
This happens with multiple computers. Is there any idea of what is happening and how we can fix it?

**Comment by peterchanws** [comment]
What Java version are you using? 32 or 64 bit?

**Comment by kieranjol** [comment]
I'll find out ASAP tomorrow! It was my colleague Margaret Vaillant that was
one of the folks with the bug. Could it be that a 32-bit version was
downloaded and caused the issue?

**Comment by peterchanws** [comment]
ePADD require 64-bit java.
