### ISSUE TITLE
Unable to see archive in Discover Module

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#366]
We have an agreement with the National Library of New Zealand to host their email archive in our epadd.stanford.edu in a pilot project. I got the file from NLNZ and cannot see them in discovery module.

**Comment by peterchanws** [comment]
In the collection-metadata.json file
Date format used in the NLNZ archive is  "16/01/1970 11:39:46 AM","lastDate":"8/04/2005 6:56:33 PM",
Date format used in the Stanford archive is "Dec 16, 2003 12:35:58 PM","lastDate":"Mar 30, 2019 3:30:47 PM"

After changing the date format, I can see the archive. Need to fix in next release.

**Comment by hangal** [comment]
Now the timestamp is a long value.
@SallyDeBauche could you please check if the NLNZ still has this archive for us to test against?
