### ISSUE TITLE
Around 1800 messages taken from Gmail have no date in ePADD

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#37]
Version epadd-standalone-jan-14
The Harrison archives reside in Gmail.
Some messages were transferred from AOL mail
I connected to the Gmail a/c to get the messages ~40,000
I exported the messages in Appraisal module.
I imported the messages in mbox format using the latestest ePADD in order to perform fine grain entity extraction.
1882 data error(s) in message content and attachments, mostly missing date.

**Comment by vihari** [comment]
@peterchanws Do you still see this in the recent import of Harrison's?
