### ISSUE TITLE
Email domain visible in discovery mode

### ISSUE THREAD

**Issue by chinuhub** [ePADD/epadd#370]
Email domain redaction not happening for all the emails in discovery mode. As a result, one can search for @stanford.edu or other mail domain to get autocomplete text.

**Comment by chinuhub** [comment]
If the algorithm can not find a name to be associated with a contact then it considers the email address as the display name for that contact. During redaction, we only redact email addresses present in the contact. However, if the display name was also an email address then the display name remains unredacted. This results in @domain appearing in correspondent entities and thus appearing in the autocompletion box. The fix includes redacting the domain name even if it appears in the display name of a contact.

**Comment by hangal** [comment]
closing because fixed.
