### ISSUE TITLE
Name of Archive Owner - ePADD Directory Name

### ISSUE THREAD

**Issue by jfarwer** [ePADD/epadd#375]
If ‘Name of Archive Owner’ is left blank when importing a set of emails then the archive gets the name 'epadd archive of '. The space as last character of the name causes trouble and trying to export to the processing module results in the error 

_Sorry, error exporting archive:   
java.io.IOException: Destination 'C:\Users\xxxx\epadd-processing\ePADD archive of \data\lexicons' directory cannot be created. Please see the log file for more details._ 

A user who is just playing around with ePADD, not setting an owner name might find it difficult figuring out what the actual problem is. As a fix the owner name could be made mandatory or alternatively in case no owner is set the blank as last character of the archive name could be removed.

**Comment by hangal** [comment]
Thanks for reporting this and the detailed report! We will try to replicate and let you know.

**Comment by hangal** [comment]
@jfarwer what did you type into the "Primary email address" field on the import screen?

**Comment by hangal** [comment]
Ok, I can replicate this by leaving both the Archive owner and primary email address fields blank.
Thanks for reporting, we'll look into a fix.
