### ISSUE TITLE
Disappearing Lexicon Categories

### ISSUE THREAD

**Issue by JoshHackel** [ePADD/epadd#377]
After creating a new Lexicon (with a category) when I open the other Lexicons all of the categories are blank. All the Lexicons (except for the one you just created) will not show any categories until you restart ePADD.

Found while in the processing module

Steps:
1) Open Lexicon search window
2) Select Create lexicon button, and give it a name
3) Select Add Category in your new Lexicon and add some values and save
4) Go back to the Lexicon search window and select a previously existing category
Result: Lexicon category table says "No data available in folder"

**Comment by hangal** [comment]
Thanks for reporting this! We can replicate the issue and will look into a fix.

**Comment by SallyDeBauche** [comment]
I tested this issue in v.7.3.4 and I can confirm that this issue is resolved. @JoshHackel would you like to try on your end?
