### ISSUE TITLE
Button for opening the sidebar sometimes obscures other content

### ISSUE THREAD

**Issue by jfarwer** [ePADD/epadd#379]
The button which opens the sidebar sometimes obscures other content. This happens especially on smaller screen sizes. Maybe reducing the button's opacity? I did this with my local ePADD version and that worked fine.
![side_panel](https://user-images.githubusercontent.com/32103096/78819735-96e47580-79ce-11ea-90ec-b8b6ee53c36f.PNG)

**Comment by hangal** [comment]
Not sure we really want to support smaller screens, btw.
There are many assumptions that might break.
Easiest might be not show the icon below a screen width, or even show a
generic message asking users to widen the window.

**Comment by jfarwer** [comment]
I see. The reduced opacity shouldn't do any harm and people here have found it useful. Maybe it works as a temporary solution? I have created a pull request.

**Comment by jfarwer** [comment]
Sorry, didn't mean to close this.
