### ISSUE TITLE
Search term not highlighted when the hits are in the To/From/cc fields

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#38]
Version: epadd.stanford.edu
The search term "dad" is hightlighted in the body of messages but not in the To/From/cc fields
![capture1](https://cloud.githubusercontent.com/assets/1050899/12520591/4af7a476-c0fa-11e5-88b0-95145c58bad3.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1050899/12520593/4c4a547c-c0fa-11e5-9271-066a7d2dc8f0.PNG)

**Comment by vihari** [comment]
I can replicate the problem that the search term is not highlighted in the to/from fields.
In the particular example that you provided, do you expect "Robert Creeley" to be highlighted when you searched for dad? Because, none of the corr. names contain the token "dad".

**Comment by peterchanws** [comment]
The corr. Dad <creeley@..> contain the token "dad".

**Comment by peterchanws** [comment]
Version Feb 19; Creeley-Full; Mac
Fixed
