### ISSUE TITLE
Names in the address book contacts appear in small case after exporting to discovery mode.

### ISSUE THREAD

**Issue by chinuhub** [ePADD/epadd#388]
This bug caused the names to appear in small case in the exported discovery archive's addressbook. This bug was a side effect of a fix for bug #370. To mask the emails appearing as names in a contact we had called 'getMaskedEmails' on all names appearing in a contact. However this method first converted all input strings to lowercase and then masked the email domain, if present. However, for non-email addresses the input got changed to lowercase because of this.

**Comment by hangal** [comment]
also download button on correspondents page in discovery gives this:
![Uploading image.png…]()

**Comment by chinuhub** [comment]
To fix it we mask only those names (posing as emails) which have @ in them.

**Comment by SallyDeBauche** [comment]
This issue seems to be resolved - it was specific to the Donald Knuth archive and the names of correspondents now appear correctly capitalized.
