### ISSUE TITLE
Addressbook download button on correspondents page in discovery gives this:

### ISSUE THREAD

**Issue by chinuhub** [ePADD/epadd#389]
also download button on correspondents page in discovery gives this:
![image](https://user-images.githubusercontent.com/1018175/95708340-9d9fbe00-0c79-11eb-9cbc-2943edfa42d5.png)

_Originally posted by @hangal in https://github.com/ePADD/epadd/issues/388#issuecomment-706869657_

**Comment by chinuhub** [comment]
downloadData.jsp and serveTmp.jsp files were not getting bundled in discovery war. They must be included in pom-discovery.xml for them to be included in standalone discovery war.

**Comment by SallyDeBauche** [comment]
I checked this issue in the Discovery module and it seems to be resolved. I was able to download addressbooks with no errors.
