### ISSUE TITLE
Information about search hits in attachment is not carried forward to processing module

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#39]
Version: epadd-standalone-jan-14.jar
Archive: Bush small
The search term "Murillo" gets 1 hit (in attachment) in the appraisal module.
It gets no hit in the processing module.
Word document attachment:
![capture1](https://cloud.githubusercontent.com/assets/1050899/12521545/07b60652-c100-11e5-920d-e704f6a6f4fc.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1050899/12521546/09078cf6-c100-11e5-84a5-31c61ec4d66c.PNG)

**Comment by vihari** [comment]
This is an excellent find and I can reproduce it, thanks.

**Comment by vihari** [comment]
@hangal Pls review this commit.

**Comment by vihari** [comment]
@hangal Please review the code.

**Comment by peterchanws** [comment]
Version Feb 19; Win 10; Bush - small
Fixed
