### ISSUE TITLE
Slower message loading on message browsing screen

### ISSUE THREAD

**Issue by chinuhub** [ePADD/epadd#390]
When searching for a term the resultset of messages gets loaded with a lot of delays sometimes even displaying the message "Unable to load the message".

**Comment by chinuhub** [comment]
In discovery mode the masking of email address in the content of the message was causing this delay. Using precompiled regex pattern helped to speed up loading.

**Comment by SallyDeBauche** [comment]
I reviewed this issue in the Discovery module and can confirm that messages are loading well and with no delays. Can we close this issue?
