### ISSUE TITLE
New Restriction Label - "Do Not Transfer to Discovery Module"

### ISSUE THREAD

**Issue by SallyDeBauche** [ePADD/epadd#392]
There is a use case for a new restriction label - "Do Not Transfer to Discovery Module." When applied, this label would prevent messages from exporting to the Discovery Module while still allowing them to export to the Delivery Module to be viewed in an institution's reading room.

**Comment by chinuhub** [comment]
To support already ingest archives we need to add the following lines in <archive dir>/data/session/LabelManager/label-info.json' file.
"-1":{"labType":"RESTRICTION","labId":"-1","labName":
    "Transfer to Delivery Only","description":
    "Transfer this message to Delivery only","isSysLabel":true,
    "restrictionType":"OTHER","restrictedUntilTime":0,"restrictedForYears":
    0}

**Comment by hangal** [comment]
This label has been added, needs to be tested and double checked in the codebase.
We should be able to close this issue after testing.

**Comment by SallyDeBauche** [comment]
I tested this feature by loading a collection processed with a previous version of ePADD. The new label was automatically added. Closing this issue.
