### ISSUE TITLE
Is running a server instance of ePADD supported?

### ISSUE THREAD

**Issue by axfelix** [ePADD/epadd#393]
Hi,

Is it possible to run ePADD on a server so that multiple users can connect on server:9099? I assumed so, but trying to run the standalone jar asks for an X11 Display, which suggests it's only supposed to be run locally...

**Comment by chinuhub** [comment]
Hi.
The command to run ePADD is 
java -Djava.io.tmpdir=/tmp -Depadd.mode.discovery=1 -Dnobrowseropen= -Xmx4g -jar epadd-discovery-standalone.jar -p <portno>

Here replace <portno> with the port number that you want to use to run ePADD. Please ensure that this port is accessible from outside and will remain open. 

Please let me know the command that you are using to run ePADD.

**Comment by axfelix** [comment]
Thanks! That works -- couldn't find it easily in the documentation.
