### ISSUE TITLE
README.md confusion

### ISSUE THREAD

**Issue by andresvia** [ePADD/epadd#394]
The readme file at the default branch, is instructing the user to download the `epadd-settings.zip` file in order to "perform correctly", however the release notes for v6.0 state that "epadd-settings is now packaged with [... os packages ...]"

I think this confusion should be clarified, since regular users tend to follow instructions verbatim, README.md should be consistent with the actual instructions.

Disclaimer: I'm not an epadd user, I was just helping my S.O. @aledelreal get started and up to speed with epadd for her research.

**Comment by SallyDeBauche** [comment]
The readme has been corrected to match the user guide.

**Comment by hangal** [comment]
resolved, so closing this issue.
