### ISSUE TITLE
Enable user to control email addresses not to be merged in any correspondents

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#40]

**Comment by hangal** [comment]
This is there now and can be controlled in the epadd-settings folder.

**Comment by peterchanws** [comment]
2 more files:
bannedStringsInPeopleNames.txt
bannedWordsInPeopleNames.txt

in addition to 
bannedStartStringsForEmailAddresses.txt

**Comment by peterchanws** [comment]
Notes about his issue dated Apr 28, 2016

# externalized banned start strings for email addresses. any email account starting with a string here will not be considered for merging.

# these strings should be in lower case.

info@
rsvp@
events@
programs@
grants@
invitations-noreply@
invitations@
office@
news@
host@
do-not-reply-
noreply-
notification
no-reply
help@

**Comment by peterchanws** [comment]
Jan 22, 2016

We're not merging based on a single name now. So "scott" will never cause a merge, as it was doing before. Similarly names or email addresses which can be controlled via lists in the epadd-settings folder will not cause a merge. So hopefully, the address book will be much more robust now. Please let me know if you see incorrect merges being performed (or correct merges not being performed). I am attaching the current versions of these files. After this is stable and we have tested it with a few archives, we can document it properly.

**Comment by peterchanws** [comment]
Done. Version 2.
