### ISSUE TITLE
Importing Mbox files gives 'Exception fetching/indexing emails' in ePADD 8

### ISSUE THREAD

**Issue by jfarwer** [ePADD/epadd#400]
When importing an Mbox file, I get an error message box with _Exception fetching/indexing emails_ coming up, and the browser stays on the Import page. Pointing the browser to the main Browse page shows that the emails have actually been imported. However, a NullPointerException was thrown during import, meaning that probably not all processes have finished correctly.

This problem seems to occur first in commit 2f1b0d1 (Merge branch 'master' into entity-CIC). Both parents of the merge work fine for me.

**Comment by jfarwer** [comment]
I downloaded epadd-standalone.jar and epadd.exe from the GitHub ePADD 8 release page.
It looks like the folder ‘epadd-settings’ which is created by running either of these is not the newest version and that is why the import doesn’t work properly. There is a link from the ePADD release page on GitHub to the installation guide and there it says

_In order for functionality for authority reconciliation to perform correctly, you must also separately download the configuration files (epadd-settings.zip), accessible via https://github.com/ePADD/epadd/releases/_

The link points back to the release page. I think it should point to the epadd-settings page (https://github.com/ePADD/epadd-settings).

**Comment by chinuhub** [comment]
There seems to be an issue with the epadd-settings folder that was packaged with build releases. This should be fixed with the release of version 8.1.
