### ISSUE TITLE
Set "Do Not Transfer" as the default message set in Export function in Appraisal and Processing

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#41]
Version 1.1
"Messages to transfer" are set as default message set in Appraisal and Processing modules. I believe users should review the emails in "Do Not Transfer"  and "Transfer with Restrictions" before they transfer the "Messages to transfer".

**Comment by hangal** [comment]
So which one should be the default?

**Comment by peterchanws** [comment]
"Do Not Transfer" should be the default.

**Comment by hangal** [comment]
Btw, the export button is currently not available on this tab.
So the user has to switch to "messages to transfer" anyway.

**Comment by vihari** [comment]
@peterchanws @hangal 
"Do not default" is the default in the latest code, so this issue is closed?

**Comment by peterchanws** [comment]
Thanks, Vihari.

**Comment by vihari** [comment]
@peterchanws Can you test this and close it if fixed.

**Comment by peterchanws** [comment]
Done.
