### ISSUE TITLE
Sometimes the email of a correspondent is used in the list of correspondents even if a name exists.

### ISSUE THREAD

**Issue by jfarwer** [ePADD/epadd#417]
After importing the corresponding Mbox file, the name John Miller is shown correctly in the list:

![Capture2](https://user-images.githubusercontent.com/32103096/131704377-5cec0fb3-2107-4ea2-abc1-f61615f80456.PNG)

However, after restart, it is the email john.miller@gmail.com that is displayed:

![Capture1](https://user-images.githubusercontent.com/32103096/131704376-bdfeab99-0f40-4f66-bcb5-6d24fb7faeb5.PNG)

This seems to happen when an Mbox file contains an email that is missing the name:

_Cc: "john.miller@gmail.com" john.miller@gmail.com_

And after that, an email containing both email and name:

_To: "John Miller" john.miller@gmail.com_

After import, ePADD correctly recognises that the name John Miller is associated with the email john.miller@gmail.com and correctly displays the name in the list of correspondents but after restarting ePADD, the list of correspondents shows the email instead.

Contacts are written to disk in serialised form, and when ePADD is restarted, contacts are deserialised. In this process, it is assumed that the line with the email address appears after a line with a name (if a name exists). If a name exists but occurs after the email, then for the contact ePADD assumes there is no name and sets the email as the name instead, and it seems that is what is happening here.

**Comment by tomhigginsuom** [comment]
This was fixed as part of the Palladium work - to be retested.

**Comment by jfarwer** [comment]
Fixed for the Palladium project and implemented in ePADD v11.0.1.
