### ISSUE TITLE
Rendering emails

### ISSUE THREAD

**Issue by LGreenP** [ePADD/epadd#420]
I’ve loaded an email archive into ePADD and notice that the display of many emails are not optimal, with line breaks not being rendered and the text being difficult to read.

I’ve captured a sample of emails and taken screen shots of how they display in ePADD. The emails are attached in the zip file as .msg and the screenshots are in the word document.

I’m using ePADD v8.1 on Windows 10 starting ePADD with 6GB RAM.

The email was imported from Exchange using Private IMAP Import option.
[Email rendering screenshots 20211110.docx](https://github.com/ePADD/epadd/files/7658430/Email.rendering.screenshots.20211110.docx)
[Email examples.zip](https://github.com/ePADD/epadd/files/7658440/Email.examples.zip)

**Comment by lgreenpd** [comment]
Updating this issue with some additional text file examples of an email not rendered cleanly. 

One file has the original message, one file has the message exported to MBOX from Apple Mail before being imported into ePADD and the third file has the message exported from ePADD into MBOX. 

Something not right along the way.

[Original email 26 October 1994.txt](https://github.com/ePADD/epadd/files/10963275/Original.email.26.October.1994.txt)
[Original email 26 October 1994 Exported to MBOX .txt](https://github.com/ePADD/epadd/files/10963276/Original.email.26.October.1994.Exported.to.MBOX.txt)
[Original email 26 October 1994 Exported to MBOX from ePADD .txt](https://github.com/ePADD/epadd/files/10963277/Original.email.26.October.1994.Exported.to.MBOX.from.ePADD.txt)

**Comment by jfarwer** [comment]
Thanks for bringing this forward. For some reason, line breaks are indeed ignored for that email. We are having a look into this.

**Comment by jfarwer** [comment]
This has been fixed in the latest release (10.0.4).

**Comment by jfarwer** [comment]
The Mac executable is available for download now.
