### ISSUE TITLE
Temurin 8 or 11 does not work?

### ISSUE THREAD

**Issue by misilot** [ePADD/epadd#426]
Hello,

I am trying to use Temurin JRE (AdoptOpenJDK) with ePADD, but it just errors out with 

>Sorry, ePADD has encountered an error with the Java version on this system. Please install the latest release of Java. 1.7.0

I think it than opens up a browser to download the official Java JRE, however we aren't licensed to use that version.

Any ideas?

Thanks!

**Comment by jfarwer** [comment]
Hi,

I don't know whether that is still relevant to you but with the newest release of ePADD Temurin should work fine.
