### ISSUE TITLE
Import summary as first page after finish import

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#44]
[Statafterimport.docx](https://github.com/ePADD/epadd/files/108549/Statafterimport.docx)

**Comment by vihari** [comment]
@peterchanws  The doc. attached is what you expect to see after finish import?

**Comment by glynnedw** [comment]
have attached a cleaner version
[ePADD rel 1_Statafterimport 44.docx](https://github.com/ePADD/epadd/files/115975/ePADD.rel.1_Statafterimport.44.docx)

**Comment by peterchanws** [comment]
ProdPad Idea#46
