### ISSUE TITLE
Issue with encoding accented characters when importing Mbox file

### ISSUE THREAD

**Issue by emelinelevasseur** [ePADD/epadd#440]
Platform : Windows 10 64 bits
RAM : 16 Go
Java :
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
Epadd : 10.0.2

There seems to be a problem with the encoding of accented characters when importing an Mbox file. Indeed, the titles of some folders have accents, and these characters are transformed in the path. For example, "é" becomes "?". As a result, the folder and the included mails are not imported. 
The result in the report : C:\Users\emeline.levasseur\Documents\01_DAD\messageries\atelier_pele_mel_20230214\Local_Folders-1\1 chantier des fonds.sbd\G?n?ralit?s messages:-1
"G?n?ralit?s" is actually "Généralités".

Thank you,

**Comment by emelinelevasseur** [comment]
Thank you !

**Comment by jfarwer** [comment]
This has been fixed in the latest release (10.0.3).

**Comment by emelinelevasseur** [comment]
Great, thank you a lot !
