### ISSUE TITLE
Uploading sidecar file on Mac creates Windows path-looking name

### ISSUE THREAD

**Issue by ives1227** [ePADD/epadd#442]
**Describe the bug**
When uploading a sidecar file to my project in ePADD, the file is being prepended with a 'C:\fakepath\' text string in the front so the literal filename is 'C:\fakepath\drsConfig.txt'.  

**To Reproduce**
**ON a MAC:**
1. Prepare a project with email data (I imported some mbox data)
2. Go to Import
3. Scroll down to Upload a Sidecar file
4. Click on the icon to upload and navigate to a predefined txt file (mine was called drsConfig.txt)
5. Click upload 

**Expected behavior**
A file called drsConfig.txt should exist in the sidecar but the file is actually called 'C:\fakepath\drsConfig.txt'.  I also verified that this is what it is named in my File System (see screenshots)

**Screenshots**
<img width="1083" alt="Screen Shot 2023-03-16 at 1 31 47 PM" src="https://user-images.githubusercontent.com/6585049/225707299-45f54470-224c-4442-bd6e-8b9e7c545225.png">
<img width="488" alt="Screen Shot 2023-03-16 at 1 45 11 PM" src="https://user-images.githubusercontent.com/6585049/225707576-91f4d93d-bac4-45e6-a415-d63a33c8176b.png">

**Desktop (please complete the following information):**
 - OS: iOs
 - Browser Chrome 109.0.5414.119 (Official Build) (x86_64)
 - ePADD Version 10.0.3
 - Java Version OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)

**Additional context**
Another user is on Windows and is not seeing this happen.

**Comment by jfarwer** [comment]
Thanks. I can confirm there is an issue with the sidecar file path on Mac. We hope to have a release with a fix ready soon.

**Comment by jfarwer** [comment]
This has been fixed in the latest release (10.0.5).
