### ISSUE TITLE
Emailchemy for ePADD PST import missing items

### ISSUE THREAD

**Issue by lyndasf** [ePADD/epadd#445]
Is there a way to set ePADD so that the entire PST is imported into Emailchemy for ePADD? We are finding that Emailchemy for ePADD is excluding Calendars, Contacts, Tasks, RSS items, and Root items. It also is not retaining the subfolder directory structure upon import into ePADD, e.g., Content/Managers is only showing as Managers as the folder. 

 - Windows 10
 - Chrome
 - ePADD Version 10.5
 - Java 19

**Comment by icgifford** [comment]
Not possible to do this unfortunately.
