### ISSUE TITLE
Error importing accession into Processing module 

### ISSUE THREAD

**Issue by juliewetherill** [ePADD/epadd#447]
**Describe the bug**
I can import an archive from the Accession module and export to Processing module. But when I attempt to import to Processing module, I get the error: **Error importing accession. Code 2, Message: Unable to import accession: null**. This happens with every archive I try to import. 

**To Reproduce**
1. Import archive to Appraisal.
2. Export from Appraisal to Processing. 
3. Try to import from Processing.

**Expected behavior**
The import from Processing module should finish without error. When I open the collection, I should see metadata for the accession on front page of the collection.

**Screenshots**
See this google doc for screenshots and error log info: [https://docs.google.com/document/d/1TPdWeuUSJ8Un79giM7sjxbcWartIr0UXuJuK1idTAVs/edit?usp=sharing](url)
Go to Issue #2. 

**Desktop (please complete the following information):**
 - Windows 11
 - Browser: Chrome
 - ePADD Version 10.0.5
 - Java Version: OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.16+8-adhoc..jdk11u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 11.0.16+8-adhoc..jdk11u, mixed mode)

**Additional context**
I was analyzing a user-reported bug and needed to upgrade to v10.0.5 because that is what the user has. I was not having this issue in 10.0.3. The user's bug (#1 in the google doc I linked above) is similar but not identical (error is slightly different) and I'm not sure it's the same bug I'm seeing.

**Comment by jfarwer** [comment]
Thanks for reporting this. I am having a look into this.

**Comment by peterchanws** [comment]
I have the same problem.

Desktop (please complete the following information):
macOS 14.3.1
Browser: Chrome 122.0.6261.69
ePADD Version 10.0.6

**Comment by jfarwer** [comment]
Do you have an existing archive in processing and you want to add an accession? Or is this an archive in appraisal you want to move to processing?

**Comment by peterchanws** [comment]
I am adding an archive to processing. I exported the archive in Appraisal to the folder "ePADD". The exported folder is named "ePADD archive of Peter Chan" by the system. I changed epadd.mode=apprisal in the properties files to processing. After that, I import the archive by pointing to the "ePADD archive of Peter Chan" folder. I started "Import Accession" and got the error message. However, I can see the archive after I click "Collection".

**Comment by jfarwer** [comment]
You can create a folder called epadd-processing in your home directory, move the archive exported from appraisal into there and start ePADD in processing mode. The archive should be picked up automatically without the need to import as an accession. Does that work?

**Comment by peterchanws** [comment]
Yes.

**Comment by jfarwer** [comment]
A new version of ePADD with a fix for importing an accession into an empty collection is going to be released this week.

We are working on a fix for importing an accession into a non-empty collection.

________________________________

**Comment by peterchanws** [comment]
Thanks for the update.

**Comment by jfarwer** [comment]
Importing an accession into an empty collection should work in ePADD [v11.0.1 Alpha](https://github.com/ePADD/epadd/releases/tag/v11.0.1-alpha).
I have created a new issue (#465) for importing an accession into a non-empty collection.
