### ISSUE TITLE
IMAP Not Working - "Invalid Password"

### ISSUE THREAD

**Issue by kantonelli** [ePADD/epadd#449]
For some reason ePADD is not able to import via IMAP. I am using the "Private IMAP Email Account" import box to import an institutional Gmail account. I've tried using both imap.gmail.com and imap.googlemail.com as the IMAP Server address. 

The error returned is "Login error # 1: Invalid password for [*********@*****.org]. Please try again." but the password is definitely correct. 

Details: Windows 11, Chrome browser, ePADD 10.0.2, JDK 19.0.2

**Comment by jfarwer** [comment]
Unfortunately in May 2022, Google stopped supporting third-party apps which access an account using only username and password. There are still ways to give ePADD access but the current version of ePADD doesn't fully support IMAP anyway. 

You can export the emails in mbox format using[ Google takeout](https://takeout.google.com/). It is pretty straightforward, let me know and I help you with that.

**Comment by kantonelli** [comment]
Thanks for your response. That's a shame it got changed. I'm surprised the latest User Guide doesn't address this, hopefully it will next time it's updated.

**Comment by jfarwer** [comment]
Hi, Unfortunately, IMAP import is no longer supported in ePADD. We will update the ePADD user guide to reflect this. For Gmail, the current workaround is to export mail to Mbox (e.g., via [Google takeout](https://takeout.google.com/)) and then import the Mbox into ePADD. Sorry for the confusion, happy to help if you need any assistance.
