### ISSUE TITLE
Exception fetching/index emails

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#455]
**Describe the bug**
Got "Exception fetching/index emails" - at the end of finishing the importing of emails in Appraisal module. 

**To Reproduce**
1. In Appraisal model, confirm the folder for mbox file
2. Click "go"
3. See error

**Expected behavior**
No error. 

**Screenshots**
<img width="932" alt="Screenshot 2024-02-28 210757" src="https://github.com/ePADD/epadd/assets/1050899/c6dc3d09-fc68-4683-be43-fb035ecdc929">

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser [chrome]
 - ePADD Version 11 alpha

also happen in
macOS 14.3.1
Chrome
ePADD Version 11 alpha

**Comment by peterchanws** [comment]
[epadd.log-02-13-24.log.gz](https://github.com/ePADD/epadd/files/14448837/epadd.log-02-13-24.log.gz)
[epadd.log-02-13-24.log.warnings.gz](https://github.com/ePADD/epadd/files/14448839/epadd.log-02-13-24.log.warnings.gz)

**Comment by jfarwer** [comment]
Thanks. Do you also have the files epadd.log and epadd.log.warnings?

**Comment by peterchanws** [comment]
[epadd.log.zip](https://github.com/ePADD/epadd/files/14449854/epadd.log.zip)
Somehow, I can see the epadd.log.warning but not epadd.log in Explorer. However, when try  to attach the files, I can only see epadd.log.

**Comment by jfarwer** [comment]
Thanks, that's helpful. Let me have a look into this.

**Comment by jfarwer** [comment]
There was indeed an issue with reading the email headers from some emails. This has been fixed in [ePADD 11.0.1 Alpha](https://github.com/ePADD/epadd/releases/tag/v11.0.1-alpha). Could you try that out please?

**Comment by peterchanws** [comment]
Same error `message.`
[epadd.zip](https://github.com/ePADD/epadd/files/14469947/epadd.zip)
<img width="771" alt="Screenshot 2024-03-01 184903" src="https://github.com/ePADD/epadd/assets/1050899/ce26a62b-d78d-4d2d-9e15-c0cab34cc7fa">
``

**Comment by jfarwer** [comment]
Thanks. This seems to be a different error. Let me have a look into this.

**Comment by peterchanws** [comment]
I've successfully used this version to process a small segment of the archives previously reported as problematic without any issues. As I'm gearing up to conduct an ePADD workshop on my Mac shortly, I'm interested in knowing if it's possible for you to release this version in a dmg format. I would greatly appreciate your assistance.

**Comment by jfarwer** [comment]
Yes, the dmg file should be added to the GitHub release this or next week.

**Comment by peterchanws** [comment]
Thanks.

**Comment by jfarwer** [comment]
The dmg file for Alpha 11.0.1 is out now:
[https://github.com/ePADD/epadd/releases/tag/v11.0.1-alpha](https://github.com/ePADD/epadd/releases/tag/v11.0.1-alpha
)

**Comment by peterchanws** [comment]
This version works fine in both Win 11 and macOS 14.4.
