### ISSUE TITLE
Generate Thumbnails for Attachments

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#456]
I discovered the "Generate Thumbnails for Attachments" option under the "More" tab. I can't find it in the user manual. Can you explain what this is?

**Comment by jfarwer** [comment]
When you browse a message with an attachment then for images like jpg and gif you see a thumbnail which you can click for a larger view of the thumbnail and download the file. For attachments like XLS, PDF, and PowerPoint, you only see a placeholder with the attachment's name (which you can click again for download). The "Generate Thumbnails for Attachments" option lets you generate thumbnails for these files. I don't think it currently works on Windows but it should work on Mac and Linux. You need LibreOffice and ImageMagick installed on your machine. In the "Generate Thumbnails for Attachments" box are the fields 'Path to soffice executable' and 'Path to convert executable'. You have to paste the corresponding paths in there (there is no file browser for selecting the executables). On my machine it is /usr/bin/libreoffice and /usr/bin/convert. To start the process click 'Create Thumbnails'. Depending on the number of attachments to convert it can take a while. If you started ePADD from the console (like java -jar epadd-standalone.jar) then you see the progress and any error messages there. 

I initially had the error message 'attempt to perform an operation not allowed by the security policy PDF', and no thumbnails were generated (this didn't only affect PDFs). I had to change the security policy in ImageMagick to make it work.

A pop-up will tell you when it is finished. The thumbnails are available straight away. You see them when you go to 'All Attachments' on the main screen or when browsing messages.

Please let me know if you have any more questions.

**Comment by peterchanws** [comment]
Thank you for the detailed explanation.
