### ISSUE TITLE
Correspondent Merge Button works in Windows 11 but not in MacOS

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#459]
**Describe the bug**

In a Windows 11 environment, clicking on a correspondent row (excluding the correspondent's name) in the "Browse Correspondents" screen highlights the corresponding row. Clicking the correspondent row again removes the highlight. Multiple correspondents can be selected, and clicking the "Merge" icon initiates the correspondent merge process. Conversely, in macOS with chrome, clicking on a correspondent does not trigger any action.  In macOS with Firefox and Edge, the response is not consistent.

**To Reproduce**
 in macOS, clicking on a correspondent does not trigger any action. In macOS with Firefox and Edge, the response is not consistent.

**Expected behavior**
same as what I can do in Windows environment.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 14.4
 - Browser chrome - trigger no action; with Firefox and Edge, the response is not consistent.
 - ePADD Version 11 alpha
 - Java Version [e.g. 11]

**Additional context**

**Comment by jfarwer** [comment]
Could you please clear the browser cache and try again?

**Comment by peterchanws** [comment]
It works fine in Incognito mode. Thanks.

**Comment by jfarwer** [comment]
Thanks. That is a common issue. We will think about using something like cache busting to deal with it.
