### ISSUE TITLE
Word Frequency

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#46]
Users would like a word frequency table
![epadd - word frequency 2016 jan 29](https://cloud.githubusercontent.com/assets/1050899/12689331/0cc8e678-c691-11e5-8b1b-75c2d2bce996.png)
 for all email messages to help them to create lexicon. (exclude a, an, the, etc.)

**Comment by glynnedw** [comment]
Is there also a simple way to exclude all those simple pronouns, adverbs, and nouns like the ones above?

**Comment by peterchanws** [comment]
I think we should output messages to txt format and ask users to use others tools to do analysis including word frequency. I take this out from enhancement and assign it back to me for more discussion.

**Comment by peterchanws** [comment]
ProdPad Idea #54
