### ISSUE TITLE
ePADD requirements

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#460]
Is the following copies from https://www.epaddproject.org/using-epadd/download-and-install still valid?

Operating Systems: Windows 7 SP1 / 11, Mac OS X 10.12 / 10.13, Ubuntu 16.04 
Memory: 8 GB RAM (4 GB RAM allocated to the application by default)
Browsers: Chrome 61 or later, Firefox 55 or later
Java: Java Runtime Environment 11 or later required.

**Comment by jfarwer** [comment]
Yes, this should still be valid.

**Comment by jfarwer** [comment]
We haven't tested on different versions of macOS yet, but they should work fine. I shall do some testing.

ePADD always takes 4GB RAM by default. You can allocate more memory by launching ePADD from the command line like this:

java -Xmx#g -jar epadd-standalone.jar

replacing # with the amount of RAM in gigabytes (GB) you want to assign. For example, to allocate 6 GB, use

java -Xmx6g -jar epadd-standalone.jar

**Comment by peterchanws** [comment]
I used java -Xmx8g -jar epadd-standalone.jar in a terminal. ePADD didn't launch. Here are the last few lines in the terminal:

Mar 21, 2024 7:28:18 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Skipped installing application listeners due to previous error(s)
Mar 21, 2024 7:28:18 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Mar 21, 2024 7:28:18 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/epadd] startup failed due to previous errors
Mar 21, 2024 7:28:18 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
WARNING: The web application [epadd] registered the JDBC driver [org.sqlite.JDBC] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Mar 21, 2024 7:28:18 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [epadd] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@a61492b]) and a value of type [org.apache.logging.log4j.core.LoggerContext] (value [org.apache.logging.log4j.core.LoggerContext@30d6d623]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Mar 21, 2024 7:28:18 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-9099"]
Splash screen is 800x400

**Comment by jfarwer** [comment]
Does it work without the memory specification just using
`java -jar epadd-standalone.jar`?

**Comment by peterchanws** [comment]
No, it doesn't work. I checked the Java in the machine and get the follwoing:

(base) pchan3@Peter-MacBook-Pro ~ % java -version 
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)
(base) pchan3@Peter-MacBook-Pro ~ %

**Comment by jfarwer** [comment]
The dmg file comes bundled with a version of Java, whereas when starting ePADD from the command line, the Java version installed on your machine is used. It seems that is Java 8 and the current version of ePADD needs at least Java 11. Could you please install a newer Java version, for example from here: [https://www.oracle.com/uk/java/technologies/downloads/#jdk17-mac](https://www.oracle.com/uk/java/technologies/downloads/#jdk17-mac)?

**Comment by peterchanws** [comment]
Great!! Thank you so much. It works now.
