### ISSUE TITLE
Exception fetching/indexing emails on importing

### ISSUE THREAD

**Issue by sshipley64** [ePADD/epadd#461]
Exception fetching/indexing emails on importing

After about 4 imports I get this error.  trying to import again gives this error.  Can provide the mboxes if needed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19GB
 - Browser chrome
 - ePADD Version 11.0.1 alpha

18 Mar 08:11:10 Util ERROR - Exception fetching/indexing emails
java.lang.NullPointerException: null
	at org.apache.jsp.ajax.async.doFetchAndIndex_jsp.doFetchAndIndex(doFetchAndIndex_jsp.java:80) ~[?:?]
	at org.apache.jsp.ajax.async.doFetchAndIndex_jsp$1.onStart(doFetchAndIndex_jsp.java:341) ~[?:?]
	at edu.stanford.epadd.util.OperationInfo.lambda$run$0(OperationInfo.java:61) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]

if try to import the same mbox again,  I get

18 Mar 09:02:01 Indexer WARN  - !!!!!!!
Index reader has 61423 doc(s) of which 909 are deleted)
!!!!!!!!!!
18 Mar 09:02:02 Indexer WARN  - Number of content docs: 61423, number deleted: 909
18 Mar 09:02:02 Indexer WARN  - Number of attachment docs: 24080, number deleted: 0
18 Mar 09:02:03 EmailDocument WARN  - Alert!: froms.length > 1: 2
18 Mar 09:02:03 EmailDocument WARN  - Sawant
18 Mar 09:02:03 EmailDocument WARN  - Kshama
18 Mar 09:02:03 EmailDocument WARN  - WARNING!: Multiple from addresses in message (2): Sawant, Kshama Message: /mnt/epadd/sawantPSTS/BITRECOVER_12-03-2024 10-55/Kshama.Sawant@seattle.gov.pst/Top of Personal Folders/Kshama.Sawant@seattle.gov (MainArchive)/Recoverable Items/DiscoveryHolds/DiscoveryHolds.mbox Msg#47c19d9d0054772d4c64ceecc9a93d9dcfca01552d958c67ba080ec6dd3b790d (Subject:UDP discussions) guessed date Jan 1, 1960
18 Mar 09:02:03 EmailDocument WARN  - Sawant
18 Mar 09:02:03 EmailDocument WARN  - Kshama
18 Mar 09:02:04 EmailDocument WARN  - WARNING!: Multiple from addresses in message (2): Sawant, Kshama Message: /mnt/epadd/sawantPSTS/BITRECOVER_12-03-2024 10-55/Kshama.Sawant@seattle.gov.pst/Top of Personal Folders/Kshama.Sawant@seattle.gov (MainArchive)/Recoverable Items/DiscoveryHolds/DiscoveryHolds.mbox Msg#47c19d9d0054772d4c64ceecc9a93d9dcfca01552d958c67ba080ec6dd3b790d (Subject:UDP discussions) guessed date Jan 1, 1960
18 Mar 09:02:04 EmailDocument WARN  - Sawant
18 Mar 09:02:04 EmailDocument WARN  - Kshama

**Comment by jfarwer** [comment]
Yes please, the mbox files would be helpful.

**Comment by sshipley64** [comment]
https://drive.google.com/file/d/1GIaVXf1fIZlmHKayv2aJD5_OEyjbQVX-/view?usp=drive_link and I did give you permissions this time.

**Comment by sshipley64** [comment]
https://drive.google.com/file/d/1jmYbpGy3fYz2NzlIG6wWVpn4heWzXrKe/view?usp=sharing
I think this is the right one.   I've upped my RAM and am trying again with a different large set of mboxes.   What RAM does the computer you have use and how much are you giving to JAVA if you don't mind me asking?

**Comment by sshipley64** [comment]
I did it step by step as I was loading as I was converting.  I’ll try all in one go and see what it does.

**Comment by sshipley64** [comment]
Did it show BITRECOVER_12-03-2024 10-55  as an empty folder?   It's showing it empty when I try to import all at once,  but it isn't.

**Comment by sshipley64** [comment]
I've loaded it by itself and then it shows folders.  I'm trying that one by itself to see if that batch is the issue. 
![10-55 folder by itself](https://github.com/ePADD/epadd/assets/10080940/a958e360-6470-4202-9540-19e43259e526)
![10-55 folder in group](https://github.com/ePADD/epadd/assets/10080940/1628be43-7c1d-45ef-94a7-042959957f38)

**Comment by jfarwer** [comment]
Yes, it shows several folders for BITRECOVER_12-03-2024 10-55. On the import screen did you use the box 'Mbox files'? Sometimes I accidentally use the box underneath 'Non-Mbox email files' and then it shows 0 messages.

**Comment by sshipley64** [comment]
No.  I tried again to make sure and all of the folder under mbox.
![mboximports](https://github.com/ePADD/epadd/assets/10080940/47b757ad-9c8b-4a42-896c-efeddfa8a363)
![ChooseFolders](https://github.com/ePADD/epadd/assets/10080940/f61f3bdf-f5f7-450a-9e6b-c7d2c77040b3)
[epaddubuntu.zip](https://github.com/ePADD/epadd/files/14765545/epaddubuntu.zip)

**Comment by jfarwer** [comment]
Could you please try putting the four BITRECOVER folders into one folder and then pointing to that folder on the import screen rather than using the 'Add folder' button?

**Comment by sshipley64** [comment]
Okay,  it did do it this time.   Should I always wait and have all the mboxes ready to go and do them all at once?  I have some collections where I've had to download 40+ psts out of MS Purview and so I have a lot of folders of mboxes.

**Comment by jfarwer** [comment]
No, there is no need to handle everything at once. When I realised you used the 'Add Folder' button on the import screen, I tested it myself and discovered a bug that occasionally prevents folders from being read correctly (as you experienced when it failed to display any messages for BITRECOVER_12-03-2024 10-55).
To work around this please put all the folders you intend to import into a single directory. Then, on the import screen direct to this directory. It should make no difference to use the 'Add Folder' button aside from the initial step of putting your folders into one location.
You can return to the import screen at any time after the initial import to add folders.
I hope this makes sense. Please let me know if you have any issues.
