### ISSUE TITLE
Multi-term search results page formatting issue

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#466]
**Describe the bug**
In the result page for Multi-term search results, the bottom banner for "ePADD Release 11.0.1-alpha © Stanford University" appears in the middle of the screen. 

**To Reproduce**
goto Multi-term search results
enter several lines of terms

**Expected behavior**
It will be nice if the banner remains in the bottom of the screen.

**Screenshots**
see attached file

**Desktop (please complete the following information):**
 - OS: macOS 14
 - Browser Chrome
 - ePADD Version 11.0.1
 - Java(TM) SE Runtime Environment (build 22+36-2370)

![Screenshot 2024-03-21 at 12 26 06](https://github.com/ePADD/epadd/assets/1050899/e579c511-7102-43c3-be02-b04f4e4f6843)

**Comment by jfarwer** [comment]
Thanks for reporting this. We aim to fix this in the next version.

**Comment by jfarwer** [comment]
Resolved in v11.0.1
