### ISSUE TITLE
Mailing List [ML]

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#467]
I understand the assignment of [ML] mailing list to an email address allow the system to filer those messages in advance search. I edited the address book for 
John Kirtley
jfk@jfkintampa.com 

to 
John Kirtley [ML]
jfk@jfkintampa.com

I saved my edit and goto Advance Search. I click "Yes" to Mailing List and press Enter and get "No matching messages."

I expect to see the email from 
John Kirtley [ML]
jfk@jfkintampa.com

When I use search "John Kirtley" in Browser Correspondent, the result is 1 email from John Kirtley.

Is my understanding of how to set an email address wrong OR
is my Advance Search operation incorrect?

**Comment by jfarwer** [comment]
This is incorrectly stated in the on-screen help where it says:

_You can designate messages as originating from a mailing list by typing -- ML after the correspondent name._

In the address book, contacts are separated by two hyphens (--). To have the [ML] tag recognized, it has to be straight after the hyphens (any white spaces in between are ignored), for example:
```
--
John
john.miller@test.com
-- [ML]
The Daily Digest
tdd@test.com
--
```
If you now search for emails from mailing lists, it will show messages from The Daily Digest.

We should correct this in the on-screen help and clarify it in the ePADD documentation.
