### ISSUE TITLE
Lexicon with special characters in name is unusable

### ISSUE THREAD

**Issue by iTReprise** [ePADD/epadd#470]
**Describe the bug**
Creating a lexicon with a special character (I tested **ü** & **ä**) creates a seemingly working lexicon but removes my abilty to interact with it as epadd chrashes when clicking on it. This prevents me from renaming it or adding/removing entries.

**Steps to Reproduce**
1. Go to **Lexicon**
2. Create a new lexicon with an **ü** or **ä**
3. Save the lexicon
4. Go back to the main page
5. Go to **Lexicon**
6. Click on the newly created lexicon

**Screenshots**
Broken encoding in lexicon list:
![grafik](https://github.com/ePADD/epadd/assets/29485072/aae02f79-a1e8-4a59-807d-983b25d950f3)

**Desktop:**
 - OS: Ubuntu 20.4
 - Browser: agnostic
 - ePADD Version: 11.0.1-alpha
 - Java Version: 17

**Comment by iTReprise** [comment]
I was unclear - you are right. ePADD doesn't crash per se, it just shows the error page but is still alive and well.
Do you still need logs?

**Comment by jfarwer** [comment]
Yes, that would be helpful.

**Comment by jfarwer** [comment]
Sorry, no I actually don't need the logs.

**Comment by jfarwer** [comment]
Thanks for reporting this. We have fixed the issue for the next ePADD 11 release. You can try it out: [SharePoint Link](https://livemanchesterac-my.sharepoint.com/:u:/g/personal/jochen_farwer_manchester_ac_uk/EZ6lxL-uSIpPpwKJ2vDpCyABbfYPJR-8AO6c2fnQf559Vg?e=74BT33).
You should have access to the file. Please let me know if it says you don't have access permission.

You might need to clear your browser cache.

**Comment by jfarwer** [comment]
Fixed in v11.0.1
