### ISSUE TITLE
Exception fetching/indexing emails

### ISSUE THREAD

**Issue by elvisvr** [ePADD/epadd#473]
**Describe the bug**
Importing a large PST file the operation was canceled and now anytime the application is launched an error screen is displayed, also any new import that's made fails with the "Exception fetching/indexing emails" error. 
I'll appreciate your support.

**To Reproduce**
1. Import the MBOX file
2. Click Next
3. Select the MBOX file
4. Click next, and error is displayed

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome
 - ePADD Version: 10.0.6
 - Java Version: 20.2.0

**Additional context**
I've added the log file for more context.
[epadd.log](https://github.com/user-attachments/files/16730119/epadd.log)

**Comment by jfarwer** [comment]
Could you please try ePADD v11.0.2 https://github.com/ePADD/epadd/releases/tag/v11.0.2?

**Comment by elvisvr** [comment]
Thank you very much, I've installed it and it's working fine, I really appreciate it.

**Comment by jfarwer** [comment]
Great. Thanks for the feedback.
