### ISSUE TITLE
dmg for v11.0.2

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#474]
I will be conducting a workshop on ePADD during the week of 9/30. I was wondering if you will release the dmg file for version 11.0.2 before 9/30.

**Comment by jfarwer** [comment]
Sorry for not having done this yet. We will do that next week. I will let you know when it is ready.

**Comment by peterchanws** [comment]
NP. Thank you for letting me know the expected date.

**Comment by tomhigginsuom** [comment]
The .dmg file is now available as part of the release - apologies for the delay:
https://github.com/ePADD/epadd/releases/tag/v11.0.2

We did encounter some issues with Apple's notarization service so unfortunately you may see some security warnings on first use (which we normally try to avoid). Once installed the application should work as normal. If we are able to resolve the warnings I will upload a new installer.
