### ISSUE TITLE
Add email source name when people add messages in mbox format

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#48]
This helps to identify the source of email messages in the folder view.

![epadd - import - source label](https://cloud.githubusercontent.com/assets/1050899/12690075/d2f07a56-c695-11e5-97cc-6aab1f10ef64.png)

**Comment by hangal** [comment]
Hi Peter, is the email source only for mbox'es? how about for Gmail/IMAP etc?

**Comment by peterchanws** [comment]
Can we use the email address(es) we enter for IMAP a/c as email sources? If not, we will have to add "Email Source" to IMAP a/c as well.

**Comment by peterchanws** [comment]
For Imap a/c, use full email address(es) as source name.

**Comment by peterchanws** [comment]
Version Jun27 
Feature added.
