### ISSUE TITLE
Re-organize Browse Page

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#49]
Location entity will include all fine type entity related to location.
Organization entity will be changed to Other Entities.
Order of the boxes have been changed as well.

![epadd - browse order update - 2016 jan 29](https://cloud.githubusercontent.com/assets/1050899/12690545/3798d0ea-c699-11e5-91df-4b479be846ce.png)

**Comment by hangal** [comment]
how about for discovery module?

**Comment by peterchanws** [comment]
Here it is.
![epadd - browse order update - discovery - 2016 feb 8](https://cloud.githubusercontent.com/assets/1050899/12903538/2eeaab1c-ce7d-11e5-8a7b-62d22e7822e9.png)
