### ISSUE TITLE
Error Importing mbox file

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#54]
Version Feb 19; Scam letters
The mbox file was exported from Thunderbird. I successfully imported it to mac mail. However, ePADD got error in import. I will send the file by email.

**Comment by hangal** [comment]
reason for problem is that some email addresses are null. We had not seen this before.
Added a defensive check now.
Thanks for reporting.
Should be fixed in feb 26 release. Please check and close if fixed.
Btw, we find only 119 messages in it,

**Comment by peterchanws** [comment]
Still got error. Log sent by email.

**Comment by hangal** [comment]
Peter, could you pls try
http://suif.stanford.edu/~hangal/epadd/epadd-standalone-feb27.jar
This works for me.

**Comment by peterchanws** [comment]
Thanks, Sudheendra. The Feb 27 version works fine. One minor issue is that the lexicon folder contain default.english.lex which didn't work. I copied general.english.lex, sensitive.english.lex, sentiments.english.lex to the lexicon and it works.
