### ISSUE TITLE
Some hits in the search for Moby Dick in Creeley didn't get highlighted

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#56]
Version Feb 26; Creeley Full
<img width="738" alt="screen shot 2016-02-29 at 10 55 58 am" src="https://cloud.githubusercontent.com/assets/1050899/13405446/4b71d5c4-ded3-11e5-92b7-8c89fc8561b5.png">

<img width="467" alt="screen shot 2016-02-29 at 10 56 16 am" src="https://cloud.githubusercontent.com/assets/1050899/13405454/50ef20a6-ded3-11e5-8093-007db7bce613.png">

**Comment by hangal** [comment]
@vihari pls check

**Comment by peterchanws** [comment]
The one that is not highlighted is Moby-Dick. So case closed.
