### ISSUE TITLE
Click on any of the tabs in browse page (starting page) is not working  

### ISSUE THREAD

**Issue by vihari** [ePADD/epadd#58]
Problem observed on Firefox and IE on Windows and Mac.
When a tab on the browse page is clicked anywhere else other than the text or arrow will redirect to a "undefined" page with a 404 problem. See screenshot
![screen shot 2016-03-05 at 12 46 51](https://cloud.githubusercontent.com/assets/3615408/13546326/72954144-e2d0-11e5-8c17-86c7e5121e81.png)

**Comment by hangal** [comment]
not reproducible.
