### ISSUE TITLE
Search results view with new facets - snippets

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#61]
![epadd - search facets - snippet view - 2016 feb 8](https://cloud.githubusercontent.com/assets/1050899/13868139/31140ebe-ec83-11e5-8617-852a62e80f69.png)

**Comment by peterchanws** [comment]
ProdPad Idea #35

**Comment by hangal** [comment]
Just a heads-up that the snippets view is not very easy, that's why we had dropped it.
Let us evaluate it.
The facets part is easier and we can do that.

**Comment by peterchanws** [comment]
I see. If it is too difficult, we can propose doing it in next grant.

**Comment by peterchanws** [comment]
Close this. Refer to Sachin's new design.
