### ISSUE TITLE
Add fields to Accession Metadata

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#76]
Add the following fields to "Collection Details":

1. Rights and conditions
2. Notes

Input:
1. "Rights and Conditions" under "Catalog Record Link"; max 200 characters.
2. "Notes" under "Contact Email Address"; max 200 characters

Display:
1. "Rights and Conditions" under "About"
2. "Notes" under "Rights and Conditions"

**Comment by hangal** [comment]
Hi Peter, where should these fields be displayed?

**Comment by peterchanws** [comment]
Display:
1. "Rights and Conditions" under "About XXX"
2. "Notes" under "Rights and Conditions"

**Comment by hangal** [comment]
ok. will it also show on collection detail page.

**Comment by peterchanws** [comment]
Version Jun27

Fields added but contents NOT displayed.

![screen shot 2016-06-27 at 7 57 10 pm](https://cloud.githubusercontent.com/assets/1050899/16402461/7d92192a-3ca1-11e6-8044-b0c099de1a89.png)


![screen shot 2016-06-27 at 7 56 55 pm](https://cloud.githubusercontent.com/assets/1050899/16402473/8c118eea-3ca1-11e6-89a1-f74de03ec34f.png)

**Comment by peterchanws** [comment]
Display:
1. "Rights and Conditions" under "About XXX" and above ENTER with fonts smaller than "About XXX"
2. "Notes" immediately under "Rights and Conditions"

**Comment by peterchanws** [comment]
Version Jul 1
Feature implemented
