### ISSUE TITLE
Advanced Search - Attachment Type "Internet File"

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#81]
Version Jun27

Advanced Search - Select Attachment Type "Internet File" should have some hits. System give No Matching Messages.

![screen shot 2016-06-27 at 9 07 12 pm](https://cloud.githubusercontent.com/assets/1050899/16403572/81c8bf30-3cab-11e6-97d5-d4e677a4897a.png)

![screen shot 2016-06-27 at 9 06 48 pm](https://cloud.githubusercontent.com/assets/1050899/16403569/76909642-3cab-11e6-826c-1e6d787fa8a7.png)

**Comment by hangal** [comment]
should be fixed now.

**Comment by peterchanws** [comment]
Version July 1
Fixed
