### ISSUE TITLE
JSP compilation error for fine grained NER

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#9]
Also, query generator is saying "epadd is off" according to Josh.

**Comment by hangal** [comment]
After fixing, @vihari can you add a JSPC precompile task to the build scripts so we know that there are no compilation errors?
Not urgent, but would be nice to have in the next week.

**Comment by hangal** [comment]
reopening so we remember to add the precompile task.
see workspace/muse/pre.build.xml for example.

**Comment by hangal** [comment]
@vihari pls add precompile task

**Comment by vihari** [comment]
@hangal Review and close.

**Comment by hangal** [comment]
closed, thanks.
