### ISSUE TITLE
ePADD.exe not working

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#94]
Version 2 final

**Comment by hangal** [comment]
hmm. that's strange. it works fine for me on the Dell (I just tried it, it gets to the import email sources screen. you cannot even get that far?).

Can you reboot or try on another system, etc?

These are the binary sizes you have, correct?

85360490 Aug 19 16:41 epadd.exe
82480807 Aug 19 16:41 epadd-discovery.exe

**Comment by peterchanws** [comment]
I am running Win 10 at home. I will find a Win 7 machine to try.

**Comment by peterchanws** [comment]
Works fine in the Win 10 machine in the lab
